src/app/app.component.html
src/applications/content-entries-app/content-entries-app.module.ts
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-access-control/bulk-access-control.component.html
src/applications/content-entries-app/entries/bulk-actions/components/bulk-access-control/bulk-access-control.component.scss
src/applications/content-entries-app/entries/bulk-actions/components/bulk-access-control/bulk-access-control.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-download/bulk-download.component.html
src/applications/content-entries-app/entries/bulk-actions/components/bulk-download/bulk-download.component.scss
src/applications/content-entries-app/entries/bulk-actions/components/bulk-download/bulk-download.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-remove-categories/bulk-remove-categories.component.html
src/applications/content-entries-app/entries/bulk-actions/components/bulk-remove-categories/bulk-remove-categories.component.scss
src/applications/content-entries-app/entries/bulk-actions/components/bulk-remove-categories/bulk-remove-categories.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/index.ts
src/applications/content-entries-app/entries/bulk-actions/services/XInternalXAddBulkDownloadAction.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-access-control.service.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-delete.service.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-download.service.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-remove-categories.service.ts
src/applications/content-entries-app/entries/bulk-actions/services/index.ts
src/applications/content-entries-app/entries/entries-components-list.ts
src/applications/content-entries-app/entries/entries-list.component.ts
src/applications/content-entries-app/entries/entries-store/entries-store.service.ts
src/i18n/en.json
src/shared/kmc-shell/providers/browser.service.ts

feat(content-entries) - Bulk operations: delete, change owner, remove from category, download, access control

---

src/app/app.routes.ts
src/applications/content-categories-app/categories/categories-components-list.ts
src/applications/content-categories-app/categories/categories-list.component.html
src/applications/content-categories-app/categories/categories-list.component.ts
src/applications/content-categories-app/category/category-components-list.ts
src/applications/content-categories-app/category/category.component.html
src/applications/content-categories-app/category/category.component.ts
src/applications/content-categories-app/content-categories-app.module.ts
src/applications/content-categories-app/content-categories-app.routes.ts
src/applications/content-categories-app/content-categories.component.html
src/applications/content-categories-app/content-categories.component.ts

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/178)

Update routing with categories

---

src/applications/content-playlists-app/content-playlists-app.module.ts
src/applications/content-playlists-app/content-playlists-app.routes.ts
src/applications/content-playlists-app/playlist/entry-can-deactivate.service.ts
src/applications/content-playlists-app/playlist/playlist-can-deactivate.service.ts
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.scss
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts
src/applications/content-playlists-app/playlist/playlist-store.service.ts
src/applications/content-playlists-app/playlist/playlist.component.html
src/applications/content-playlists-app/playlist/playlist.component.ts
src/applications/content-playlists-app/playlists/pipes/playlist-type.pipe.ts
src/i18n/en.json

---
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' height=40></a>
<a href='https://www.codereviewhub.com/kaltura/kmc-ng/pull/177?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' …

Playlist fixes

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-delete.service.ts
src/applications/content-entries-app/entries/entries-list.component.ts
src/applications/content-playlists-app/content-playlists-app.module.ts
src/applications/content-playlists-app/content-playlists-app.routes.ts
src/applications/content-playlists-app/content-playlists.component.ts
src/applications/content-playlists-app/playlist/playlist-components-list.ts
src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.html
src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.scss
src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.ts
src/applications/content-playlists-app/playlist/playlist-entries-table/playlist-entries-table.component.html
src/applications/content-playlists-app/playlist/playlist-entries-table/playlist-entries-table.component.scss
src/applications/content-playlists-app/playlist/playlist-entries-table/playlist-entries-table.component.ts
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.scss
src/applications/content-playlists-app/playlist/playlist-store.service.ts
src/applications/content-playlists-app/playlist/playlist.component.scss
src/applications/content-playlists-app/playlists/bulk-service/bulk-delete.service.ts
src/applications/content-playlists-app/playlists/pipes/playlist-type.pipe.ts
src/applications/content-playlists-app/playlists/playlists-list.component.html
src/applications/content-playlists-app/playlists/playlists-list.component.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/environments/environment.ts
src/i18n/en.json

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/174)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/kaltura/kmc-ng/pull/174%23issuecomment-31540587 …

Playlists bulk

---

src/applications/content-entries-app/entries/entries-store/entries-store.service.ts
src/applications/content-entries-app/entries/pipes/entry-duration.pipe.ts
src/applications/content-entries-app/entry/entry-sections-list/entry-sections-list-handler.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

feat: support external media entries

---

src/app/components/app-menu/app-menu.component.html
src/app/components/app-menu/app-menu.component.scss
src/app/components/app-menu/app-menu.component.ts
src/app/components/user-settings/user-settings.component.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

fix: update localization logic and help menu style

---

src/applications/settings-account-settings-app/settings-account-settings.component.html
src/applications/settings-account-settings-app/settings-account-settings.component.scss
src/applications/settings-account-settings-app/settings-account-settings.component.ts
src/applications/settings-account-upgrade-app/settings-account-upgrade.component.html
src/applications/settings-account-upgrade-app/settings-account-upgrade.component.scss
src/i18n/en.json

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

style: Settings

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-handler.ts
src/applications/content-entries-app/entry/entry-captions/entry-captions.component.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts
src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts
src/i18n/en.json
src/shared/kmc-shell/providers/browser.service.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

refactor: download API refactor for captions, related, flavors, bulk upload

---

src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.ts

- [] Feature
- [] Yes
- [] No
---
--- …

fix: validate flavor file before upload, show error if file size exceed

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-handler.ts
src/applications/content-entries-app/entry/entry-captions/new-entry-caption-file.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts
src/applications/content-entries-app/entry/entry-flavours/flavor.ts
src/applications/content-entries-app/entry/entry-flavours/new-entry-flavour-file.ts
src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts
src/applications/content-entries-app/entry/entry-related/entry-related.component.html
src/applications/content-entries-app/entry/entry-related/new-entry-related-file.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

Entry uploads refactoring

---

src/i18n/en.json

- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/224)

Bulk Actions: Dropdown's label should be "More Actions"

---

src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.html

…custom data profiles
- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/227)

Metadata: Adding short tags does not work

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-action-base.service.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-delete.service.ts

- [] Feature
- [] Yes
- [] No
---
--- …

fix: show specific error message on bulk delete error

---

src/shared/content-shared/categories-tree/categories-tree.component.scss

- [] Feature
- [] Yes
- [] No
---
--- …

fix: caterories-tree style

---

src/applications/administration-roles-app/roles/roles-list.component.scss
src/applications/administration-roles-app/roles/roles-table.component.scss

- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/236)

KMCNG-785 Roles table is not full width under IE11 and MS Edge

---

package-lock.json
package.json
src/applications/content-entries-app/entry/entry-captions/entry-captions-handler.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours-handler.ts
src/applications/content-entries-app/entry/entry-related/entry-related-handler.ts
src/applications/content-upload-control-app/upload-list/pipes/upload-status.pipe.ts
src/applications/content-upload-control-app/upload-list/upload-list-table.component.html
src/applications/content-upload-control-app/upload-list/upload-list-table.component.scss
src/applications/content-upload-control-app/upload-list/upload-list-table.component.ts
src/applications/content-upload-control-app/upload-list/upload-list.component.html
src/applications/content-upload-control-app/upload-list/upload-list.component.ts
src/applications/content-upload-control-app/upload-list/upload-progress/upload-progress.component.ts
src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts
src/i18n/en.json
src/shared/kmc-shell/new-entry-upload/new-entry-upload-file.ts
src/shared/kmc-shell/new-entry-upload/new-entry-upload.service.ts

- [] Bugfix
- [] Yes
- [] No
---
--- …

Resume upload

---

src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts
src/applications/content-entries-app/entry/entry-metadata/entry-metadata-handler.ts
src/i18n/en.json
src/shared/content-shared/categories-store.service.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

fix: Kmcng 678

---

src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts
src/applications/content-entries-app/entry/entry-metadata/entry-metadata-handler.ts
src/i18n/en.json
src/shared/content-shared/categories-store.service.ts

- [] Feature
- [] Yes
- [] No
---
--- …

fix: KMCNG-678

---

src/app/app.module.ts
src/applications/content-entries-app/entry/entry-preview/entry-preview-handler.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-handler.ts
src/applications/content-entries-app/preview-metadata-changed-event.ts
src/shared/kmc-shared/app-events/app-event.ts
src/shared/kmc-shared/app-events/app-events.module.ts
src/shared/kmc-shared/app-events/app-events.service.ts
src/shared/kmc-shared/app-events/index.ts
src/shared/kmc-shared/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/243)

App events

---

package-lock.json
package.json
src/applications/content-categories-app/categories/add-new-category/add-new-category.component.html
src/applications/content-categories-app/categories/add-new-category/add-new-category.component.ts
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-category-listing/bulk-change-category-listing.component.html
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-category-listing/bulk-change-category-listing.component.ts
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-content-privacy/bulk-change-content-privacy.component.html
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-content-privacy/bulk-change-content-privacy.component.ts
src/applications/content-categories-app/categories/categories-components-list.ts
src/applications/content-categories-app/category/category.component.ts
src/applications/content-entries-app/entries/entries-list-holder.component.ts
src/applications/content-entries-app/entry/entry-details/entry-details.component.html
src/applications/content-entries-app/entry/entry-details/entry-details.component.ts
src/applications/content-playlists-app/playlist/playlist-details/playlist-details.component.ts
src/applications/content-playlists-app/playlist/playlist-sections-list/playlist-sections-list.component.ts
src/applications/content-playlists-app/playlist/playlist-sections.ts
src/applications/content-playlists-app/playlist/playlist-store.service.ts
src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts
src/shared/content-shared/entries-list/entries-list.component.ts
src/shared/content-shared/entries-store/entries-store.service.ts
src/shared/kmc-shell/auth/app-authentication.service.ts
src/shared/kmc-shell/new-entry-upload/new-entry-upload.module.ts
src/shared/kmc-shell/new-entry-upload/new-entry-upload.service.ts

- [] Feature
- [] Yes
- [] No
---
--- …

fix: ability to compile in the prod mode

---

src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-875 fix: allow user to save related file without file type

---

src/applications/content-categories-app/categories/categories-table/categories-table.component.ts
src/applications/kmc-upload-app/create-live/kaltura-live-stream/kaltura-live-stream.component.ts
src/applications/kmc-upload-app/prepare-entry/transcoding-profile-select/transcoding-profile-select.component.ts
src/applications/kmc-upload-app/upload-settings/upload-settings.component.scss
src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts

- [] Feature
- [] Yes
- [] No
---
--- …

Fix ie and build

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.ts
src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts
src/applications/content-entries-app/entry/entry-captions/entry-captions.component.html
src/applications/content-entries-app/entry/entry-captions/new-entry-caption-file.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.ts
src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts
src/applications/content-entries-app/entry/entry-related/entry-related.component.html
src/applications/content-entries-app/entry/entry-related/new-entry-related-file.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-widget.service.ts
src/applications/kmc-upload-app/bulk-upload-menu/bulk-upload-menu.component.html
src/applications/kmc-upload-app/bulk-upload-menu/bulk-upload-menu.component.ts
src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts
src/i18n/en.json

- [] Feature
- [] Yes
- [] No
---
--- …

Check all entry sections that uploading files and make sure they handle relevant statuses

---

package-lock.json
package.json
src/app-config/index.ts
src/app/app.module.ts
src/applications/content-entries-app/entry/entry-captions/entry-captions.component.ts
src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-related/entry-related-widget.service.ts

upgrade kaltura-client-typescript to include fixes for file upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/275)

chore: upgrade kaltura-typescript-client library

---

src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-widget.service.ts

fix(content-entry): scroll page to top when deleting flavors and thumbnails

---

src/shared/kmc-shared/dynamic-metadata-form/dynamic-metadata-form.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/288)

fix: allow empty field for escaping

---

src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts

…simulation mode in player V2
- [] Feature
Entries without mobile flavors are not playable in Entry details preview player
Entries without mobile flavors are playable in Entry details preview player
- [] Yes
--- …

fix(content-entry): Enable preview of entry without mobile flavors

---

src/shared/kmc-shared/dynamic-metadata-form/dynamic-metadata-section-factory.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/296)

move logic from kaltura-ng to kmc-ng

---

src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts

fix: detect file type from upper case file extensions as well

---

src/applications/content-upload-control-app/upload-list/upload-list.component.ts
src/i18n/en.json

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1074

---

src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-scheduling/bulk-scheduling.component.ts
src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts
src/applications/content-entries-app/entry/entry-scheduling/entry-scheduling-widget.service.ts
src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata-widget.service.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/298)

fix: enable save button when user update complex form

---

package-lock.json
src/applications/content-bulk-log-app/bulk-log-store/bulk-log-store.service.ts
src/applications/content-bulk-log-app/bulk-log-tags/bulk-log-tags.component.html
src/applications/content-bulk-log-app/bulk-log-tags/bulk-log-tags.component.ts
src/shared/content-shared/entries-list/entries-list-tags.component.html
src/shared/content-shared/entries-list/entries-list-tags.component.ts
src/shared/content-shared/entries-list/entries-list.component.ts
src/shared/content-shared/entries-refine-filters/entries-refine-filters.component.ts
src/shared/content-shared/entries-store/entries-store.service.ts
tsconfig.json

- fix the tooltip in the tags 
- check pageSize before setting it to store (to prevent warning in console)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/307)

Fix filters tooltip

---

src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts

refactoring flavor loading logic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/313)

refactor: entry flavor loading

---

src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.scss
src/shared/kmc-shared/dynamic-metadata-form/dynamic-metadata-section-factory.service.ts

support new dynamic form control help tip

---

src/applications/kmc-upload-app/upload-settings/upload-settings.component.html

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1195

---

src/shared/kmc-shared/dynamic-metadata-form/dynamic-metadata-form.ts

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1128

---

src/applications/kmc-upload-app/prepare-entry/prepare-entry.service.ts
src/applications/kmc-upload-app/upload-monitor/bulk-upload-monitor.service.ts

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1160

---

src/app/components/login/login.component.ts

seems not only IE has this problem
- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1191

---

src/applications/kmc-upload-app/upload-settings/upload-settings.component.html
src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1196

---

src/applications/content-bulk-log-app/content-bulk-log-app.component.ts
src/applications/content-drop-folders-app/content-drop-folders.component.ts
src/applications/content-entries-app/content-entries.component.ts
src/applications/content-playlists-app/content-playlists.component.ts
src/applications/kmc-upload-app/kmc-upload-app.module.ts
src/applications/kmc-upload-app/upload-monitor/bulk-upload-monitor.service.ts
src/applications/kmc-upload-app/upload-monitor/drop-folders-monitor.service.ts
src/applications/kmc-upload-app/upload-monitor/upload-monitor-section/upload-monitor-section.component.html
src/applications/kmc-upload-app/upload-monitor/upload-monitor-section/upload-monitor-section.component.scss
src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.html
src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts
src/i18n/en.json

* use recover function if possible
* do not show drop-folders section if user has no permission to use drop-folders
- [] Feature
- [] Yes
- [] No
---
**Any background …

KMCNG-1178, KMCNG-1092 + without ticket (details in review)

---

src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.html
src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.scss
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-playlists-app/playlists/playlists-list/playlists-list.component.ts
src/shared/content-shared/entries-refine-filters/entries-refine-filters.component.html
src/shared/content-shared/entries-refine-filters/entries-refine-filters.component.scss

fix: entries and playlists delete confirmation message fixes, refine filter calendar widgets layout fix

---

src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-live/entry-live.component.html

fix(content-entry): DVR window parameter: display N/A when dvrWindow is NaN

---

src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-widget.service.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

fix(content-entry): Entry Thumbnail - verify selected file size and issue an alert if larger than 2GB (prevent upload in this case)

---

src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts

fix(content-entry): refresh player preview on flavors refresh (user clicks the refresh button)

---

src/app/components/login/login.component.ts
src/applications/content-entries-app/entry/entry-details/entry-details.component.html
src/applications/content-playlists-app/playlist/playlist-details/playlist-details.component.html

fix(content-entry): fix date pipe format to display correct hours and minutes

---

src/applications/content-categories-app/categories/categories.service.ts
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/manage-end-user-permissions-table/manage-end-user-permissions-table.component.html

…ot siblings show message
When toggling 'inherit users permissions' flag to YES
and entering the manage users the dropdowns of permission level and update method are enabled although all the other inputs are not
- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/337)

Bug fixes 

---

src/app/components/app-menu/app-menu.component.html
src/applications/content-categories-app/categories/categories-list/categories-list.component.html
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html
src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.scss
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.scss
src/applications/content-playlists-app/playlist/playlist-sections-list/playlist-sections-list.component.scss
src/applications/content-playlists-app/playlist/playlist.component.scss
src/i18n/en.json
src/shared/content-shared/entries/entries-selector/entries-selector.component.scss

fix: layout fixes for playlists on Safari + user settings popup positioning

---

src/applications/content-playlists-app/playlist/playlist-content/playlist-content-widget.service.ts
src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.html
src/applications/content-playlists-app/playlist/playlist-content/playlist-entries-table/playlist-entries-table.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/341)

Playlist bulk issue

---

src/applications/content-categories-app/category/category-entitlements/category-entitlements.component.html
src/applications/content-categories-app/category/category-entitlements/category-entitlements.component.scss
src/applications/content-categories-app/category/category-entitlements/change-owner/change-owner.component.html
src/applications/content-categories-app/category/category-entitlements/change-owner/change-owner.component.ts
src/applications/content-categories-app/content-categories-app.module.ts
src/applications/kmc-upload-app/create-live/create-live.component.ts
src/i18n/en.json

- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/340)

Ben bug fixes

---

src/app-config/index.ts
src/applications/administration-roles-app/roles/roles-table.component.html
src/applications/administration-users-app/users/users-table.component.html
src/applications/content-bulk-log-app/bulk-log-table/bulk-log-table.component.html
src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.ts
src/applications/content-categories-app/categories/categories-refine-filters/categories-refine-filters.component.ts
src/applications/content-categories-app/categories/categories-table/categories-table.component.html
src/applications/content-categories-app/category/category-entitlements/category-entitlements-widget.service.ts
src/applications/content-categories-app/category/category-entitlements/category-entitlements.component.html
src/applications/content-categories-app/category/category-entitlements/category-entitlements.component.ts
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/add-users/add-users.component.html
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/add-users/add-users.service.ts
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/manage-end-user-permissions-table/manage-end-user-permissions-table.component.html
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/manage-end-user-permissions.component.html
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/manage-end-user-permissions.component.ts
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/manage-end-user-permissions.service.ts
src/applications/content-categories-app/category/category-subcategories/category-subcategories-table/category-subcategories-table.component.html
src/applications/content-categories-app/category/category.service.ts
src/applications/content-categories-app/content-categories-app.module.ts
src/applications/content-drop-folders-app/drop-folders-table/drop-folders-table.component.html
src/applications/content-playlists-app/playlist/playlist-content/playlist-entries-table/playlist-entries-table.component.html
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.html
src/applications/content-upload-control-app/upload-list/upload-list-table.component.html
src/i18n/en.json
src/shared/content-shared/entries/entries-table/entries-table.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/342)

multiple changes

---

src/applications/content-moderation-app/entries/entries-list-holder.component.html
src/applications/content-moderation-app/entries/entries-list-holder.component.ts
src/applications/content-playlists-app/playlist/playlist-add-entry/playlist-add-entry.component.html
src/applications/content-playlists-app/playlist/playlist-add-entry/playlist-add-entry.component.ts
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts
src/shared/content-shared/entries/entries-list/entries-list.component.html
src/shared/content-shared/entries/entries-list/entries-list.component.ts
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.ts
src/shared/content-shared/entries/entries-selector/entries-selector.component.html
src/shared/content-shared/entries/entries-selector/entries-selector.component.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

- please check 'moderation' for implementation of default filters
- please check 'manual playlist > content > add entry' for enforced filters
NOTE:
- please  pull kaltura-ng master and build before reviewing this branch.
- in moderation you will not see the desired label in the tags, this is ok since I'm going to fix it once I support the restore of filters later this week
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/346)

feat: pre-define entries list with enforced filters and default filters

---

src/applications/content-categories-app/categories/categories.service.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/352)

prevent reset of sort filters

---

src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.scss

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1269

---

src/applications/content-moderation-app/entry-report/entry-report.component.ts

fix(content-moderation): send admin KS to player to enable playback of moderated entries

---

src/applications/preview-and-embed/preview-embed.component.ts

fix: sort player names in Share & Embed screen alphabetically disregarding casing

---

src/shared/content-shared/entries/entries-store/entries-store-data-provider.service.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1372
add `moderationCount` into response profile
- [] Yes
---
--- …

KMCNG-1372

---

src/applications/administration-users-app/users/users-table.component.html
src/applications/content-bulk-log-app/bulk-log-tags/bulk-log-tags.component.ts
src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.ts
src/applications/content-categories-app/category/category-details/category-details.component.html
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/manage-end-user-permissions-table/manage-end-user-permissions-table.component.html
src/applications/content-drop-folders-app/drop-folders-tags/drop-folders-tags.component.ts
src/applications/content-entries-app/entry/entry-details/entry-details.component.html
src/applications/content-playlists-app/playlist/playlist-details/playlist-details.component.html
src/applications/content-playlists-app/playlists/playlists-tags/playlists-tags.component.ts
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts

check this branch together with the following [kaltura-ng branch](https://github.com/kaltura/kaltura-ng/pull/80)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/374)

changed locale format into fixed formats

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.scss
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.ts
src/applications/settings-custom-data-app/schemas/schemas-list/schemas-list.component.html
src/applications/settings-custom-data-app/schemas/schemas-list/schemas-list.component.ts

- [] Feature
cancellation of schema editing works properly
- [] Yes
---
--- …

remove binding between input schema and fields array

---

src/applications/settings-custom-data-app/schemas/pipes/custom-schema-type.pipe.ts

- [] Bugfix
- [] Feature
- [] Yes
- [] No
---
--- …

Fix custom metadata's field type icon

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1308
remove preconvert from the list of allowed statuses, motivation - 
- [] Yes
- [] No
---
**Any background …

KMCNG-1308

---

src/applications/content-categories-app/category/category.service.ts
src/i18n/en.json

- [] Yes
- [] No
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

KMCNG-1295

---

src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.html
src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts
src/applications/content-drop-folders-app/drop-folders-store/drop-folders-store.service.ts
src/applications/content-drop-folders-app/drop-folders-table/drop-folders-table.component.html
src/applications/content-drop-folders-app/drop-folders-table/drop-folders-table.component.ts

- [] Feature
- [] Yes
- [] No
---
--- …

KMCNG-1270

---

src/app/app.component.html
src/app/app.component.scss
src/applications/content-categories-app/categories/new-category/new-category.component.ts

fix(content-categories): confirm closing the new category window if the form is dirty or a folder was selected by the user

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-entries-app/entries/bulk-actions/services/bulk-add-categories.service.ts
src/i18n/en.json

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1325
Add warning that entry is already assigned to category
- [] Yes
---
**Any background context you want to …

KMCNG-1325

---

src/applications/content-categories-app/category/category.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/385)

fix reference id comparison when reference id is null

---

src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content.component.ts

- [] Feature
If user select entries before saving the selection is still visible
Clear selection on save
- [] Yes
---
--- …

Clear selection on save for manual playlist

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-fields-table/custom-schema-fields-table.component.html
src/i18n/en.json
src/shared/kmc-shared/custom-metadata/kaltura-metadata-parser.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/389)

fix mapping of field name/label/key

---

src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.html
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/bulk-operations/bulk-operations.component.html
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.html
src/applications/content-moderation-app/entries/entries-list-holder.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/395)

fix: close bulk menu upon scrolling of several views

---

src/applications/content-bulk-log-app/bulk-log-tags/bulk-log-tags.component.ts
src/applications/content-categories-app/categories/categories-list/categories-list-tags.component.ts
src/applications/content-drop-folders-app/drop-folders-table/drop-folders-table.component.ts
src/applications/content-drop-folders-app/drop-folders-tags/drop-folders-tags.component.ts
src/applications/content-playlists-app/playlists/playlists-tags/playlists-tags.component.ts
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts

- [] Bugfix
- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/396)

refactor: Replaced moment with DatePipe from kaltura-ui

---

package.json
src/applications/content-categories-app/category/category.component.scss
src/applications/content-entries-app/content-entries-app.module.ts
src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-live/entry-live.component.html
src/applications/content-entries-app/entry/entry-live/entry-live.component.ts
src/applications/content-entries-app/entry/entry.component.scss
src/configuration/server-config.json
src/configuration/server-config.template.json
src/configuration/server-config.ts
src/i18n/en.json

feat: Kaltura live screen in entry details

---

src/applications/administration-roles-app/roles/roles-table.component.ts
src/applications/administration-users-app/users/users-table.component.ts
src/applications/content-bulk-log-app/bulk-log-table/bulk-log-table.component.ts
src/applications/content-categories-app/categories/categories-table/categories-table.component.ts
src/applications/content-categories-app/category/category-subcategories/category-subcategories-table/category-subcategories-table.component.ts
src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.ts
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.ts
src/applications/content-syndication-app/feeds/feeds-table/feeds-table.component.ts
src/applications/settings-custom-data-app/schemas/schemas-table/schemas-table.component.ts
src/applications/settings-integration-settings-app/entitlement/entitlement-table/entitlement-table.component.html
src/applications/settings-integration-settings-app/entitlement/entitlement-table/entitlement-table.component.ts
src/shared/content-shared/entries/entries-table/entries-table.component.ts

- [] Bugfix
- [] Feature
build menu in several places including access control is using a wrong logic which leaves the selected item in place. should do as in drop folder but always rebuild the menu
always rebuild a menu
- [] Yes
- [] No
---
**Any background context you want to …

fix menu building + some codestyle

---

src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts

- [] Feature
1. Set ownership of entry to some user
2. Remove this user from the system
3. Go to entry details > users tab
4. Tab can't be loaded due to server error ("INVALID_USER_ID")
Show owner name even if the account was removed (as it's done in the legacy system)
- [] Yes
- [] No
If this PR contains a breaking change, please describe the impact and …

Fix Entry Details > Users tab

---

src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-list/transcoding-profiles-list.component.ts

- [] Bugfix
- [] Feature
Delete and setAsDefault actions for transcoding profiles don't have block-shell
Blocking shell on performing those operations
- [] Yes
- [] No
---
---
This …

Add missing block-shell for transcoding actions

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts

- [] Feature
Can't save entry's custom data created in settings>custom metadata
Add `md_` prefix to generated field id (according to the legacy)
- [] Yes
- [] No
---
**Any …

fix custom schema field id creation

---

src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.html

fix: drop folders filters dropdown layout fix

---

src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1303
- [] Yes
- [] No
---
--- …

KMCNG-1303

---

src/applications/content-playlists-app/playlist/playlist.component.html
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-lists-holder/transcoding-profiles-lists-holder.component.html

fix(content/playlist): set correct position for confirmation message in playlist and transcoding settings

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts
src/i18n/en.json

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1441
- [] Yes
- [] No
---
--- …

fix(settings/custom-data): set explicit header for cancel confirmation

---

src/applications/administration-users-app/users/edit-user/edit-user.component.html
src/applications/administration-users-app/users/edit-user/edit-user.component.scss
src/applications/administration-users-app/users/edit-user/edit-user.component.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1417
- [] Yes
- [] No
---
--- …

KMCNG-1417

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata-widget.service.ts
src/i18n/en.json

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1416
- [] Yes
- [] No
---
--- …

KMCNG-1416

---

src/applications/administration-users-app/users/users.service.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1420
- [] Yes
- [] No
---
--- …

fix(administration/users): display error message returned from server for invalid user names

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-948
https://kaltura.atlassian.net/browse/KMCNG-1147
- [] Yes
- [] No
---
**Any background context you want to …

KMCNG-948, KMCNG-1147

---

src/applications/content-categories-app/categories/new-category/new-category.component.html
src/applications/content-categories-app/categories/new-category/new-category.component.scss
src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.html
src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.scss
src/applications/settings-integration-settings-app/entitlement/new-entitlement/new-entitlement.component.scss
src/shared/content-shared/categories/categories-tree/categories-tree.component.html
src/shared/content-shared/categories/categories-tree/categories-tree.component.scss
src/shared/content-shared/categories/category-selector/category-selector.component.scss

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1387
https://kaltura.atlassian.net/browse/KMCNG-1389
https://kaltura.atlassian.net/browse/KMCNG-1414
- [] Yes
- [] No
---
**How should this be manually …

KMCNG-1387, KMCNG-1389, KMCNG-1414

---

src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts

- [] Feature
If a user tries to apply changes in entry details > metadata > category selector popup discard changes window pop up
Do not show confirmation on apply
- [] Yes
- [] No
---
**How should this be …

Allow close without confirmation on apply action

---

src/applications/content-categories-app/categories/move-category/move-category.component.html
src/applications/content-categories-app/categories/move-category/move-category.component.ts
src/applications/content-categories-app/categories/new-category/new-category.component.html
src/applications/content-categories-app/categories/new-category/new-category.component.ts
src/i18n/en.json
src/shared/content-shared/categories/category-selector/category-selector.component.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1294
- [] Yes
- [] No
---
--- …

KMCNG-1294

---

src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-category-listing/bulk-change-category-listing.component.ts
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts
src/applications/content-entries-app/entry/entry-users/entry-users.component.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1409
- [] Yes
- [] No
---
--- …

KMCNG-1409

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.scss
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1446
- [] Yes
- [] No
---
--- …

KMCNG-1446

---

src/applications/content-bulk-log-app/bulk-log-table/bulk-log-table.component.html

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1133
https://kaltura.atlassian.net/browse/KMCNG-1094
The bugs themselves were fixed already, I've just added tooltips for columns that aren't fully visible 
- [] Yes
- [] No
---
**Where should …

KMCNG-1094, KMCNG-1133

---

src/applications/content-upload-control-app/upload-list/upload-list-table.component.html
src/applications/content-upload-control-app/upload-list/upload-list-table.component.ts
src/applications/kmc-upload-app/upload-settings/upload-settings.component.scss
src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-889
https://kaltura.atlassian.net/browse/KMCNG-912
https://kaltura.atlassian.net/browse/KMCNG-921
- [] Yes
- [] No
---
**How should this be manually …

KMCNG-889, KMCNG-912, KMCNG-921

---

src/i18n/en.json

- [] Feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/454)

fix: KMCNG-714 - Flavors: Wrong error message when loading flavors fails

---

src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.html
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.ts
src/i18n/en.json

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1324
https://kaltura.atlassian.net/browse/KMCNG-1393
- [] Yes
- [] No
---
**Any background context you want to …

KMCNG-1324, KMCNG-1393

---

src/applications/content-playlists-app/playlists/add-new-playlist/add-new-playlist.component.html

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1291
- [] Yes
- [] No
---
--- …

KMCNG-1291

---

src/applications/content-bulk-log-app/bulk-log-refine-filters/bulk-log-refine-filters.component.ts
src/i18n/en.json

- [] Feature
https://kaltura.atlassian.net/browse/KMCNG-1169
- [] Yes
- [] No
---
--- …

KMCNG-1169

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-entries-app/entry/entry-scheduling/entry-scheduling-widget.service.ts
src/applications/content-entries-app/entry/entry-scheduling/entry-scheduling.component.html
src/applications/content-entries-app/entry/entry-scheduling/entry-scheduling.component.ts
src/applications/content-entries-app/entry/entry.component.html
src/applications/content-entries-app/entry/entry.component.ts
src/shared/content-shared/entries/scheduling/scheduling.component.html
src/shared/content-shared/entries/scheduling/scheduling.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/510)

Implement permission CONTENT_MANAGE_SCHEDULE

---

src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails.component.html
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails.component.ts
src/applications/content-entries-app/entry/entry.component.html
src/applications/content-entries-app/entry/entry.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/511)

Implement permission CONTENT_MANAGE_THUMBNAIL

---

src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/501)

Entry Details > Metadata: remove redundant code

---

src/__local_machine_only__/README.md
src/applications/studio-app/studio.component.ts
src/configuration/server-config-utils.ts
src/configuration/server-config.json
src/configuration/server-config.template.json
src/configuration/server-config.ts
src/shared/kmc-shell/auth/app-authentication.service.ts
src/shared/kmc-shell/auth/app-user.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/528)

feat: Studio integration

---

src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/add-users/add-users.component.html
src/applications/content-categories-app/category/category-entitlements/manage-end-user-permissions/add-users/add-users.component.scss
src/i18n/en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/545)

fixed: KMCNG-1530 - Categories: UI issues in Add Users window

---

package-lock.json
package.json
src/applications/administration-roles-app/roles-table/roles-table.component.ts
src/applications/administration-users-app/users/users-table.component.ts
src/applications/content-bulk-log-app/bulk-log-table/bulk-log-table.component.ts
src/applications/content-categories-app/categories/categories-table/categories-table.component.ts
src/applications/content-categories-app/category/category-subcategories/category-subcategories-table/category-subcategories-table.component.ts
src/applications/content-drop-folders-app/drop-folders-table/drop-folders-table.component.ts
src/applications/content-entries-app/entries/entries-list-holder.component.ts
src/applications/content-entries-app/entry/entry-captions/entry-captions.component.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.ts
src/applications/content-entries-app/entry/entry-related/entry-related.component.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails.component.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rules-table/playlist-rules-table.component.ts
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.ts
src/applications/content-syndication-app/feeds/feeds-table/feeds-table.component.ts
src/applications/settings-access-control-app/profiles/profiles-table/profiles-table.component.html
src/applications/settings-access-control-app/profiles/profiles-table/profiles-table.component.scss
src/applications/settings-access-control-app/profiles/profiles-table/profiles-table.component.ts
src/applications/settings-custom-data-app/schemas/schemas-table/schemas-table.component.ts
src/applications/settings-integration-settings-app/entitlement/entitlement-table/entitlement-table.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-table/transcoding-profiles-table.component.scss
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-table/transcoding-profiles-table.component.ts
src/shared/content-shared/entries/entries-list/entries-list.component.ts
src/shared/content-shared/entries/entries-table/entries-table.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/554)

fix: set delete action color to red in all menus

---

src/applications/administration-roles-app/administration-roles.component.ts
src/applications/administration-roles-app/permissions-table/permissions-table.component.ts
src/applications/administration-roles-app/roles-list/roles-list.component.ts
src/applications/administration-roles-app/roles-store/roles-store.service.ts

Utilize KalturaLogger to log administration > roles module 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/562)

KalturaLogger logs: administration > roles module 

---

src/applications/content-bulk-log-app/bulk-log-list/bulk-log-list.component.ts
src/applications/content-bulk-log-app/bulk-log-store/bulk-log-store.service.ts
src/applications/content-bulk-log-app/content-bulk-log-app.component.ts
src/i18n/en.json

Utilize KalturaLogger to log content > bulk-log module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/561)

KalturaLogger logs: content > bulk-log module

---

src/applications/settings-integration-settings-app/account-info/account-info.component.ts
src/applications/settings-integration-settings-app/entitlement/edit-entitlement/edit-entitlement.component.ts
src/applications/settings-integration-settings-app/entitlement/entitlement.component.html
src/applications/settings-integration-settings-app/entitlement/entitlement.component.ts
src/applications/settings-integration-settings-app/entitlement/new-entitlement/new-entitlement.component.ts

Utilize KalturaLogger to log settings > integration module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/560)

KalturaLogger logs: settings > integration module

---

src/applications/settings-account-settings-app/settings-account-settings.component.ts

Utilize KalturaLogger to log settings > account settings module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/559)

KalturaLogger logs: settings > account settings module

---

src/applications/settings-account-information-app/account-info/account-info.component.ts
src/applications/settings-account-information-app/settings-account-information.component.ts

Utilize KalturaLogger to log settings > account information module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/558)

KalturaLogger logs: settings > account information module

---

src/applications/settings-my-user-settings-app/change-password/change-password.component.ts
src/applications/settings-my-user-settings-app/edit-email-address/edit-email-address.component.ts
src/applications/settings-my-user-settings-app/edit-user-name/edit-user-name.component.ts
src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts
src/applications/settings-my-user-settings-app/settings-my-user-settings.service.ts

Utilize KalturaLogger to log settings > my user settings module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/557)

KalturaLogger logs: settings > my user settings module

---

src/applications/settings-transcoding-settings-app/settings-transcoding-settings.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/edit-live-flavor/edit-live-flavor.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/edit-media-flavor/edit-media-flavor.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/transcoding-profile-flavors.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/add-new-profile/add-new-profile.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-list/transcoding-profiles-list.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-lists-holder/transcoding-profiles-lists-holder.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-store/base-transcoding-profiles-store.service.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-store/live-transcoding-profiles-store.service.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-store/media-transcoding-profiles-store.service.ts

Utilize KalturaLogger to log settings > transcoding module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/556)

KalturaLogger logs: settings > transcoding module

---

src/applications/settings-access-control-app/profiles/edit-profile/edit-profile.component.ts
src/applications/settings-access-control-app/profiles/profiles-list/profiles-list.component.ts
src/applications/settings-access-control-app/profiles/profiles-store/profiles-store.service.ts
src/applications/settings-access-control-app/settings-access-control.component.ts

Utilize KalturaLogger to log settings > access control module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/555)

KalturaLogger logs: settings > access control module 

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.ts
src/applications/settings-custom-data-app/schemas/schemas-list/schemas-list.component.ts
src/applications/settings-custom-data-app/schemas/schemas-store/schemas-store.service.ts

Utilize KalturaLogger to log settings > custom data module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/553)

KalturaLogger logs: settings > custom data module

---

src/applications/settings-access-control-app/profiles/edit-profile/edit-profile.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1615
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/574)

KMCNG-1615

---

src/applications/settings-access-control-app/profiles/edit-profile/edit-profile.component.html
src/applications/settings-access-control-app/profiles/edit-profile/edit-profile.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/572)

KMCNG-1619

---

src/applications/content-entries-app/entries/entries-list-holder.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1592
https://kaltura.atlassian.net/browse/KMCNG-890
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/564)

KMCNG-890, KMCNG-1592

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/587)

fix log statement

---

src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts
src/applications/content-moderation-app/entry-report/entry-report.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/549)

Implement permission FEATURE_DISABLE_KMC_KDP_ALERTS

---

src/applications/content-categories-app/category/category-metadata/category-metadata.component.scss
src/applications/content-entries-app/entry/entry-metadata/entry-metadata.component.scss
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata.component.scss
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-metadata/transcoding-profile-metadata.component.scss

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/591)

fix: updated metadata layout

---

src/applications/kmc-upload-app/bulk-upload-menu/bulk-upload-menu.component.html
src/applications/kmc-upload-app/bulk-upload-menu/bulk-upload-menu.component.ts
src/applications/kmc-upload-app/kmc-upload-app.module.ts

https://kaltura.atlassian.net/browse/KMCNG-1515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/492)

Implement permission ADMIN_USER_BULK

---

src/applications/analytics-kava-app/analytics-kava.component.ts
src/applications/content-entries-app/entries/entries-list-holder.component.ts
src/applications/content-entries-app/entry/entry-advertisements/entry-advertisements.component.ts
src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts
src/shared/content-shared/entries/live-dashboard-host/live-dashboard-host.component.ts
src/shared/kmc-shared/kedit-hoster/kedit-hoster.service.ts
src/shared/kmc-shared/kmc-views/component-views/advertisements-app-view.service.ts
src/shared/kmc-shared/kmc-views/component-views/clip-and-trim-app-view.service.ts
src/shared/kmc-shared/kmc-views/component-views/index.ts
src/shared/kmc-shared/kmc-views/component-views/kava-app-view.service.ts
src/shared/kmc-shared/kmc-views/component-views/live-dashboard-app-view.service.ts
src/shared/kmc-shared/kmc-views/details-views/index.ts
src/shared/kmc-shared/kmc-views/kmc-component-view-base.service.ts
src/shared/kmc-shared/kmc-views/kmc-views.module.ts

https://trello.com/c/44Gmf4BE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/612)

implement component views for external apps

---

src/shared/kmc-shared/kmc-views/details-views/content-category-view.service.ts
src/shared/kmc-shared/kmc-views/details-views/content-entry-view.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/618)

chore: enable sections by permissions for entry and category details

---

src/applications/content-entries-app/entry/entry-preview/entry-preview-widget.service.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-capture.component.html
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-capture.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/625)

fix: fix player protocol config

---

src/applications/content-categories-app/category/category.service.ts
src/shared/kmc-shared/kmc-views/details-views/content-category-view.service.ts

https://trello.com/c/gPI0oPPU
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/626)

Fix categories navigation

---

src/applications/administration-roles-app/edit-role/edit-role.component.html
src/applications/administration-roles-app/edit-role/edit-role.component.ts
src/applications/administration-roles-app/permissions-table/permissions-table.component.html

https://kaltura.atlassian.net/browse/KMCNG-1538
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/631)

KMCNG-1538

---

src/applications/content-categories-app/categories/categories-refine-filters.service.ts
src/applications/content-categories-app/categories/default-filters-list.ts
src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts
src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts
src/shared/content-shared/entries/entries-store/entries-refine-filters.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/630)

Implement METADATA_PLUGIN_PERMISSION permission

---

src/applications/kmc-upload-app/create-live/create-live.component.html
src/applications/kmc-upload-app/create-live/create-live.component.ts
src/applications/kmc-upload-app/create-live/universal-live/universal-live.component.html
src/applications/kmc-upload-app/create-live/universal-live/universal-live.component.ts
src/applications/kmc-upload-app/create-live/universal-live/universal-live.service.ts
src/applications/kmc-upload-app/upload-menu/upload-menu.component.html
src/applications/kmc-upload-app/upload-menu/upload-menu.component.ts
src/applications/preview-and-embed/preview-embed.component.html
src/applications/preview-and-embed/preview-embed.component.ts
src/applications/settings-account-information-app/settings-account-information.service.ts
src/applications/settings-integration-settings-app/entitlement/entitlement.component.html
src/applications/settings-integration-settings-app/entitlement/entitlement.component.ts
src/configuration/server-config-schema.ts
src/configuration/server-config.ts
src/i18n/en.json
src/kmc-app/components/app-menu/app-menu.component.html
src/kmc-app/components/app-menu/app-menu.component.ts
src/kmc-app/components/login/forgot-password-form/forgot-password-form.component.html
src/kmc-app/components/login/forgot-password-form/forgot-password-form.component.ts
src/kmc-app/components/login/login.component.html
src/kmc-app/components/login/login.component.ts
src/shared/kmc-shell/auth/app-authentication.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/633)

fix: allow removing configuration properties

---

src/kmc-app/components/error/error.component.ts
src/shared/kmc-shell/providers/browser.service.ts

https://trello.com/c/gqchusB6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/643)

Navigate user to default page if trying to deep link into error page

---

src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-store.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/640)

Fix prev/next navigation after profile was saved

---

src/__local_machine_only__/README.md
src/configuration/server-config-example.json
src/configuration/server-config-schema.ts
src/configuration/server-config.template.json
src/configuration/server-config.ts
src/shared/kmc-shared/kedit-hoster/kedit-hoster.component.ts
src/shared/kmc-shared/kmc-views/component-views/advertisements-app-view.service.ts
src/shared/kmc-shared/kmc-views/component-views/clip-and-trim-app-view.service.ts
src/shared/kmc-shared/kmc-views/component-views/index.ts
src/shared/kmc-shared/kmc-views/component-views/quiz-app-view.service.ts
src/shared/kmc-shared/kmc-views/kmc-views.module.ts

https://trello.com/c/4pIMpQ3M
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/644)

Unify advertisements and clip&trim into single external app 'editor'

---

src/__local_machine_only__/README.md
src/applications/usage-dashboard-app/usage-dashboard.component.ts
src/configuration/server-config-example.json
src/configuration/server-config-schema.ts
src/configuration/server-config.template.json
src/configuration/server-config.ts

- upgraded our `__local-machine-only` folder
- removed unused configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/646)

upgrade usage dashboard external application to v1.0.0

---

src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-table/transcoding-profiles-table.component.html

https://kaltura.atlassian.net/browse/KMCNG-1625
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/571)

KMCNG-1625

---

src/configuration/server-config-example.json
src/configuration/server-config-schema.ts
src/configuration/server-config.template.json
src/configuration/server-config.ts
src/kmc-app/components/login/login.component.ts
src/kmc-app/kmc-app-config.ts
src/shared/kmc-shell/auth/app-authentication.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/647)

add defaultPrivileges to runtime configuration

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.scss
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.html
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1466
https://kaltura.atlassian.net/browse/KMCNG-1467
https://kaltura.atlassian.net/browse/KMCNG-1527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/664)

KMCNG-1466,KMCNG-1467, KMCNG-1527

---

src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/661)

KMCNG-1660

---

src/applications/content-categories-app/categories/categories.service.ts
src/applications/content-categories-app/categories/new-category/new-category.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/660)

KMCNG-1671

---

src/applications/kmc-upload-app/upload-settings/upload-settings.component.html
src/applications/kmc-upload-app/upload-settings/upload-settings.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/658)

KMCNG-1681

---

src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1753
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/655)

KMCNG-1753

---

src/applications/administration-users-app/users/edit-user/edit-user.component.ts
src/applications/administration-users-app/users/users.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/654)

KMCNG-1415

---

src/applications/content-syndication-app/feeds/feed-details/feed-details.component.html
src/applications/content-syndication-app/feeds/feeds.service.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1634
https://kaltura.atlassian.net/browse/KMCNG-1635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/662)

KMCNG-1634, KMCNG-1635

---

src/applications/settings-integration-settings-app/entitlement/edit-entitlement/edit-entitlement.component.html
src/applications/settings-integration-settings-app/entitlement/edit-entitlement/edit-entitlement.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/659)

KMCNG-1674

---

src/kmc-app/components/user-settings/user-settings.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/657)

KMCNG-1685

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1533
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/652)

KMCNG-1533

---

src/applications/administration-users-app/users/edit-user/edit-user.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/651)

KMCNG-1666

---

src/applications/administration-users-app/users/edit-user/edit-user.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/650)

KMCNG-1686

---

src/applications/content-categories-app/category/category-entitlements/category-entitlements-widget.service.ts
src/applications/content-categories-app/category/category-metadata/category-metadata-widget.service.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-scheduling/bulk-scheduling.component.ts
src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts
src/applications/content-entries-app/entry/entry-scheduling/entry-scheduling-widget.service.ts
src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts
src/applications/content-playlists-app/playlist/playlist-metadata/playlist-metadata-widget.service.ts
src/applications/content-syndication-app/feeds/feed-details/destinations-forms/google-destination-form/google-destination-form.component.ts
src/applications/content-syndication-app/feeds/feed-details/destinations-forms/itunes-destination-form/itunes-destination-form.component.ts
src/applications/content-syndication-app/feeds/feed-details/destinations-forms/yahoo-destination-form/yahoo-destination-form.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-metadata/transcoding-profile-metadata-widget.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/648)

KMCNG-1734

---

src/applications/content-entries-app/entry/entry-editor/entry-editor.component.html
src/shared/kmc-shared/kedit-hoster/kedit-hoster.component.ts
src/shared/kmc-shared/kmc-views/component-views/quiz-app-view.service.ts

https://trello.com/c/UwH6R2Ws
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/645)

Provide relevant kea config and handle events

---

src/applications/content-categories-app/category/category-subcategories/category-subcategories-widget.service.ts
src/shared/content-shared/categories/categories-search.service.ts

see reproducing scenario in KMCNG-1276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/666)

propgate category partnerSortValue value from service

---

src/applications/content-categories-app/category/category.service.ts
src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts
src/applications/content-entries-app/entry/entry-store.service.ts
src/applications/content-moderation-app/entry-report/entry-report.component.ts
src/applications/kmc-upload-app/prepare-entry/prepare-entry.component.ts
src/shared/kmc-shared/kedit-hoster/kedit-hoster.component.ts
src/shared/kmc-shared/kmc-views/details-views/content-category-view.service.ts
src/shared/kmc-shared/kmc-views/details-views/content-entry-view.service.ts

- make sure you check the navigation to entry from drop list (both when has network and when offline)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/667)

refactor: use openById() of view api correctly

---

src/applications/settings-integration-settings-app/entitlement/new-entitlement/new-entitlement.component.ts
src/i18n/en.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/668)

fix(settings/integration-settings): display confirmation message before adding entitlement to category

---

src/applications/administration-users-app/users/edit-user/edit-user.component.html
src/applications/administration-users-app/users/edit-user/edit-user.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/673)

KMCNG-1758

---

src/applications/content-entries-app/entries/bulk-actions/components/bulk-remove-categories/bulk-remove-categories.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/663)

KMCNG-1588

---

src/applications/analytics-live-app/analytics-live-app.module.ts
src/applications/analytics-live-app/analytics-live.component.html
src/applications/analytics-live-app/analytics-live.component.scss
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/676)

KMCNG-1777

---

src/applications/content-entries-app/entry/entry-users/entry-users.component.ts

https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/498368519/Pre-GA+test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/698)

Fix change owner - allow saving not registered username

---

src/kmc-app/components/app-menu/app-menu.component.html
src/kmc-app/components/app-menu/app-menu.component.ts
src/kmc-app/components/user-settings/user-settings.component.html
src/kmc-app/components/user-settings/user-settings.component.ts

https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/498368519/Pre-GA+test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/697)

Fix username update in the menu

---

src/applications/content-entries-app/entry/entry-access-control/entry-access-control.component.html
src/applications/content-entries-app/entry/entry-access-control/entry-access-control.component.scss
src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.html
src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.scss
src/applications/kmc-upload-app/upload-monitor/upload-monitor.component.ts

https://kaltura.atlassian.net/wiki/spaces/KMCng/pages/498368519/Pre-GA+test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/696)

Fix ui issues

---

src/i18n/en.json
src/kmc-app/components/dashboard/dashboard.component.html
src/kmc-app/components/dashboard/dashboard.component.scss
src/kmc-app/components/dashboard/dashboard.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/699)

feat: welcome screen placeholder

---

src/shared/content-shared/entries/entries-selector/entries-selector.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/702)

KMCNG-1653

---

src/shared/kmc-shared/custom-metadata/metadata-profile-store.service.ts

https://kaltura.atlassian.net/projects/KMCNG/issues/KMCNG-1849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/704)

KMCNG-1849

---

src/applications/settings-account-settings-app/settings-account-settings.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1813
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/703)

KMCNG-1813

---

src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.html
src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.scss
src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-media-button/replace-media-button.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/714)

KMCNG-1881

---

src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/718)

KMCNG-1893

---

src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.html
src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.scss
src/applications/content-entries-app/entry/entry-flavours/entry-flavours.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/710)

KMCNG-1888

---

src/applications/content-entries-app/entry/entry-metadata/entry-metadata-widget.service.ts
src/applications/content-entries-app/entry/entry.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/719)

KMCNG-1896

---

src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.html

https://kaltura.atlassian.net/browse/KMCNG-1886
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/713)

KMCNG-1886

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1890
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/712)

KMCNG-1890

---

package-lock.json
src/kmc-app/app.module.ts
src/kmc-app/app.routes.ts
src/kmc-app/components/login/login.component.ts
src/shared/kmc-shell/auth/app-authentication.service.ts
src/shared/kmc-shell/auth/app-bootstrap.service.ts

see: https://kaltura.atlassian.net/browse/KMCNG-1870
closes #716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/729)

KMCNG-1870 adjustments

---

src/applications/settings-account-information-app/settings-account-information.component.ts
src/applications/settings-account-settings-app/settings-account-settings.component.ts

https://kaltura.atlassian.net/projects/KMCNG/issues/KMCNG-1876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/708)

KMCNG-1876

---

src/shared/kmc-shared/dynamic-metadata-form/dynamic-metadata-section-factory.service.ts

https://kaltura.atlassian.net/projects/KMCNG/issues/KMCNG-1481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/684)

KMCNG-1481

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.html
src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/projects/KMCNG/issues/KMCNG-1605
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/686)

KMCNG-1605

---

src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-file/replace-file.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/715)

KMCNG-1884

---

src/kmc-app/components/changelog/changelog-content/changelog-content.component.html
src/shared/content-shared/entries/entries-table/entries-table.component.html
src/shared/content-shared/entries/entries-table/entries-table.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/738)

fix(content/entries): fix entries table column style to work on older Safari versions + update changelog

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule-parser.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1908
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/742)

KMCNG-1908

---

src/shared/content-shared/entries/entries-store/default-filters-list.ts

https://kaltura.atlassian.net/browse/KMCNG-1809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/731)

KMCNG-1809

---

src/applications/content-entries-app/entry/entry-metadata/category-selector/categories-selector.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1680
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/723)

KMCNG-1680

---

src/applications/content-syndication-app/feeds/feed-details/destinations-forms/itunes-destination-form/itunes-destination-form.component.html
src/applications/content-syndication-app/feeds/feed-details/destinations-forms/itunes-destination-form/itunes-destination-form.component.scss
src/applications/content-syndication-app/feeds/feed-details/destinations-forms/itunes-destination-form/itunes-destination-form.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/727)

KMCNG-1796

---

src/applications/content-entries-app/entry/entry-details/entry-details.component.html
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/722)

KMCNG-1800

---

src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/kmc-upload-app/create-live/create-live.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1953
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/753)

KMCNG-1953

---

src/applications/kmc-upload-app/upload-settings/upload-settings.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/755)

KMCNG-1954

---

src/applications/content-bulk-log-app/bulk-log-table/bulk-log-table.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1831
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/758)

KMCNG-1831

---

src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-file/replace-file.component.html
src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-file/replace-file.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1877
https://kaltura.atlassian.net/browse/KMCNG-1879
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/760)

KMCNG-1877, KMCNG-1879

---

src/applications/administration-users-app/users/edit-user/edit-user.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1866
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/762)

KMCNG-1866

---

src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1909
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/763)

KMCNG-1909

---

src/applications/content-entries-app/entry/entry-live/entry-live.component.html

https://kaltura.atlassian.net/browse/KMCNG-1956
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/765)

KMCNG-1956

---

src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/766)

KMCNG-1900

---

src/applications/content-entries-app/entry/entry-store.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1894
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/768)

KMCNG-1894

---

package-lock.json
package.json

@amirch1 you will need to delete node_modules, reinstall (npm run i) and setup repo (npm run setup)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/773)

fix noex issue

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.ts
src/shared/kmc-shared/language-options/language-options.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/781)

fix(content/entry): fix entry caption language selection upon editing

---

src/applications/kmc-upload-app/upload-menu/upload-menu.component.html
src/applications/kmc-upload-app/upload-menu/upload-menu.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/771)

KMCNG-1958

---

src/applications/administration-roles-app/edit-role/edit-role.component.html
src/applications/administration-roles-app/edit-role/edit-role.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/KMCNG-1843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/770)

KMCNG-1843

---

src/applications/settings-access-control-app/profiles/profiles-table/profiles-table.component.html
src/applications/settings-access-control-app/profiles/profiles-table/profiles-table.component.scss

https://kaltura.atlassian.net/browse/KMCNG-1901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/764)

KMCNG-1901

---

src/applications/content-categories-app/categories/new-category/new-category.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/759)

KMCNG-1246

---

src/applications/administration-users-app/users/edit-user/edit-user.component.html
src/applications/administration-users-app/users/edit-user/edit-user.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/724)

KMCNG-1690

---

src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/786)

fix: handle entries in which the entry creator was deleted from the system

---

src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/767)

KMCNG-1892

---

src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-action-base.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-add-tag.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-change-category-listing.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-change-content-privacy.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-change-contribution-policy.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-change-owner.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-delete.service.ts
src/applications/content-categories-app/categories/bulk-actions/services/categories-bulk-remove-tag.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1931
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/756)

KMCNG-1931

---

src/applications/content-categories-app/category/category.service.ts
src/shared/kmc-shared/kmc-views/kmc-details-view-base.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/741)

KMCNG-1920

---

src/shared/kmc-shared/kmc-views/details-views/reach-app-view.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/788)

fix: check for "content manage > edit category" and "content manage > modify caption" permissions when enabling Reach

---

src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content.component.html
src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content.component.ts
src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.html
src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/789)

KMCNG-1997

---

src/configuration/server-config-example.json
src/configuration/server-config-schema.ts
src/configuration/server-config.template.json
src/configuration/server-config.ts
src/i18n/en.json
src/kmc-app/components/app-menu/app-menu.component.html
src/kmc-app/components/app-menu/app-menu.component.scss
src/kmc-app/components/app-menu/app-menu.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/791)

fix: update support text and link

---

src/applications/services-dashboard-app/services-dashboard-app.module.ts
src/applications/services-dashboard-app/services-dashboard-app.routes.ts
src/applications/services-dashboard-app/services-dashboard.component.html
src/applications/services-dashboard-app/services-dashboard.component.scss
src/applications/services-dashboard-app/services-dashboard.component.ts
src/i18n/en.json
src/kmc-app/app.routes.ts
src/shared/kmc-shared/kmc-views/details-views/reach-app-view.service.ts
src/shared/kmc-shared/kmc-views/kmc-main-views.service.ts
src/shared/kmc-shared/kmc-views/kmc-views.module.ts
src/shared/kmc-shared/kmc-views/main-views/index.ts
src/shared/kmc-shared/kmc-views/main-views/services-dashboard-main-view.service.ts
src/shared/kmc-shared/reach-frame/reach-frame.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/792)

Add services dashboard

---

src/applications/content-entries-app/entry/entry.component.ts

https://kaltura.atlassian.net/browse/KMCNG-2024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/793)

KMCNG-2024

---

src/shared/kmc-shared/kedit-hoster/kedit-hoster.component.ts

https://kaltura.atlassian.net/browse/KMCNG-1968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/795)

KMCNG-1968

---

src/shared/content-shared/entries/entries-table/entries-table.component.html

https://kaltura.atlassian.net/browse/KMCNG-2031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/796)

KMCNG-2031

---

src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts

https://kaltura.atlassian.net/browse/KMCNG-2026
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/794)

KMCNG-2026

---

src/shared/kmc-shell/new-entry-create-from-url/new-entry-create-from-url.service.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/798)

fix(upload): set entry name and format for entries created from URL

---

src/applications/preview-and-embed/preview-and-embed.service.ts
src/applications/preview-and-embed/preview-embed.component.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/800)

fix(share-and-embed): List all V2 players in the partner account

---

src/applications/preview-and-embed/preview-and-embed.service.ts
src/applications/preview-and-embed/preview-embed.component.html
src/applications/preview-and-embed/preview-embed.component.scss
src/applications/preview-and-embed/preview-embed.component.ts
src/i18n/en.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/801)

feat: support V3 players

---

src/applications/analytics/analytics-frame.component.ts

support preserving filters in url via query params

---

src/applications/analytics/analytics-frame.component.ts

Fix preserving filters issue

---

src/applications/analytics/analytics-frame.component.ts

Fix analytics filter

---

src/applications/analytics/analytics-frame.component.ts
src/shared/kmc-shell/providers/browser.service.ts

Analytics scroll to event

---

src/applications/content-syndication-app/content-syndication-app.module.ts
src/applications/content-syndication-app/feeds/feed-details/feed-details.component.html
src/applications/content-syndication-app/feeds/feed-details/feed-details.component.ts
src/applications/content-syndication-app/feeds/feeds-list/feeds-list.component.html
src/applications/content-syndication-app/feeds/feeds-list/feeds-list.component.ts
src/applications/content-syndication-app/feeds/feeds.service.ts
src/shared/kmc-shared/searchable-dropdown/index.ts
src/shared/kmc-shared/searchable-dropdown/searchable-dropdown.component.html
src/shared/kmc-shared/searchable-dropdown/searchable-dropdown.component.scss
src/shared/kmc-shared/searchable-dropdown/searchable-dropdown.component.ts
src/shared/kmc-shared/searchable-dropdown/searchable-dropdown.module.ts

https://kaltura.atlassian.net/browse/SUP-16528

SUP-16528 Syndication feeds are not created for some playlists

---

src/applications/analytics/analytics-frame.component.ts
src/shared/kmc-shell/kmc-logs/kmc-logger-configurator.ts

Send logs to analytics

---

src/shared/kmc-shell/kmc-logs/kmc-logger-configurator.ts

Prevent start recording logs by default

---

src/kmc-app/components/app-menu/app-menu.component.html

Clickable analytics logo

---

src/applications/analytics/analytics-frame.component.ts
src/applications/content-entries-app/entry/entry.component.html
src/applications/content-entries-app/entry/entry.component.scss
src/applications/content-entries-app/entry/entry.component.ts
src/i18n/en.json

chore: Add "view analytics" button from entry details page

---

src/applications/analytics/analytics.component.ts

Hide live analytics from menu if there's no permissions

---

src/applications/analytics/analytics.component.ts

chore: Comment analytics/content-interactions from menu

---

docs/kaltura-internal-docs/contextual-help.csv
docs/kaltura-internal-docs/contextual-help.template.csv
src/applications/analytics/analytics.component.ts
src/public/contextual-help.json
src/shared/kmc-shared/kmc-views/main-views/analytics-main-view.service.ts

chore: Analytics contextual help

---

src/applications/settings-my-user-settings-app/edit-email-address/edit-email-address.component.html
src/applications/settings-my-user-settings-app/edit-email-address/edit-email-address.component.scss
src/applications/settings-my-user-settings-app/edit-email-address/edit-email-address.component.ts
src/applications/settings-my-user-settings-app/settings-my-user-settings.component.html
src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts
src/applications/settings-my-user-settings-app/settings-my-user-settings.service.ts

https://kaltura.atlassian.net/browse/KMCNG-2106

fix(settings/my-user-settings): Fix Email editing feature

---

src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts

https://kaltura.atlassian.net/browse/KMCNG-2100

KMCNG-2100

---

src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts
src/applications/content-entries-app/entry/entry-users/entry-users.component.html
src/i18n/en.json

https://kaltura.atlassian.net/browse/SUP-17743
https://kaltura.atlassian.net/browse/SUP-17356

feat(entry/users): Add co-viewers form field

---

src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-widget.service.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails.component.html

feat(entry/thumbnails): display tags in entry thumbnails table

---

src/applications/settings-my-user-settings-app/change-password/change-password.component.html
src/applications/settings-my-user-settings-app/edit-user-name/edit-user-name.component.html
src/kmc-app/components/login/login-form/login-form.component.html
src/kmc-app/components/login/login-form/login-form.component.ts
src/kmc-app/components/login/password-expired-form/password-expired-form.component.html
src/kmc-app/components/login/restore-password-form/restore-password-form.component.html
src/shared/kmc-shell/directives/prevent-password-autofill.directive.ts
src/shared/kmc-shell/kmc-shell.module.ts

https://kaltura.atlassian.net/browse/KMCNG-2102

fix: prevent passwords auto filling 

---

src/applications/content-entries-app/entry/entry-live/entry-live.component.html
src/applications/content-entries-app/entry/entry.component.html
src/applications/content-entries-app/entry/entry.component.scss
src/applications/content-entries-app/entry/entry.component.ts

chore: move "go live" button in entry header

---

src/applications/preview-and-embed/preview-embed.component.html
src/applications/preview-and-embed/preview-embed.component.ts

fix(share & embed): Refresh player when switching embed types to properly render thumbnail embed

---

src/applications/content-entries-app/entry/entry.component.ts

https://kaltura.atlassian.net/browse/AN-751

fix(entry/details): hide old analytics link if not available

---

src/i18n/en.json

https://kaltura.atlassian.net/browse/AN-744

chore: update live dashboard en translation

---

src/applications/content-entries-app/entry/components/toggle-live/live-data-request-factory.ts
src/applications/content-entries-app/entry/components/toggle-live/toggle-live.service.ts

https://kaltura.atlassian.net/browse/AN-752

fix(entry/live): update go live button status upon polling

---

src/i18n/en.json
src/kmc-app/components/login/login.component.ts

fix(login): update password of 2FA account should redirect to login page

---

src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-editors/bulk-add-editors.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-publishers/bulk-add-publishers.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-tags/bulk-add-tags.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-viewers/bulk-add-viewers.component.ts

https://kaltura.atlassian.net/browse/KMCNG-2147

fix(entries/bulk-actions): prevent app crash on bulk edit

---

src/applications/analytics/analytics-frame.component.ts

fix(analytics): provide date format in analytics config

---

src/applications/content-entries-app/entry/entry.component.html

https://kaltura.atlassian.net/browse/AN-792

chore(entry/live): hide toggle live button

---

package-lock.json
package.json
src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.html
src/applications/content-entries-app/entry/entry-captions/entry-captions-edit.component.ts
src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts
src/applications/settings-my-user-settings-app/change-password/change-password.component.html
src/applications/settings-my-user-settings-app/change-password/change-password.component.scss
src/applications/settings-my-user-settings-app/change-password/change-password.component.ts
src/applications/settings-my-user-settings-app/settings-my-user-settings.component.html
src/applications/settings-my-user-settings-app/settings-my-user-settings.component.ts
src/applications/settings-my-user-settings-app/settings-my-user-settings.service.ts
src/shared/kmc-shared/upload-management/kaltura-upload-adapter.service.ts
src/shared/kmc-shell/auth/app-authentication.service.ts
src/shared/kmc-shell/auth/app-user.ts

chore: support SCC caption type and support 2FA accounts when changing password from user settings

---

src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.ts
src/applications/content-drop-folders-app/drop-folders-refine-filters/drop-folders-refine-filters.component.html
src/applications/content-drop-folders-app/drop-folders-refine-filters/drop-folders-refine-filters.component.ts
src/applications/content-drop-folders-app/drop-folders-store/drop-folders-refine-filters.service.ts
src/applications/content-drop-folders-app/drop-folders-store/drop-folders-store.service.ts
src/applications/content-drop-folders-app/drop-folders-tags/drop-folders-tags.component.ts
src/i18n/en.json

https://kaltura.atlassian.net/browse/SUP-19384

fix(content/drop-folders): add missing drop folders filter by folder name

---

src/kmc-app/components/multiAccount/multi-account.component.ts
src/styles/app-theme/styles.scss

fix: Multi account menu style fixes

---

src/applications/analytics/analytics-frame.component.ts

fix: analytics navigation approach

---

src/applications/analytics/analytics-frame.component.ts

https://kaltura.atlassian.net/browse/AN-936

feat(AN-936): provide previous url upon navigation

---

src/applications/administration-users-app/users/users-table.component.ts
src/i18n/en.json

feat(administration/users): add user analytics drill-down action

---

src/applications/content-drop-folders-app/drop-folders-store/drop-folders-store.service.ts
src/configuration/global-config.ts

https://kaltura.atlassian.net/browse/SUP-19722

chore: load up to 500 drop folders

---

src/applications/analytics/analytics-frame.component.ts

fix(entry-live): store live entry users reports format in localstorage

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-entries-data-provider.service.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule.component.ts
src/i18n/en.json
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.ts
src/shared/content-shared/entries/entries-store/default-filters-list.ts
src/shared/content-shared/entries/entries-store/entries-refine-filters.service.ts
src/shared/content-shared/entries/entries-store/entries-store-data-provider.service.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

https://kaltura.atlassian.net/browse/KMCNG-1805

feat(entries/refine-filter): Filter for entries with YouTube entries

---

src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.ts

chore: fix Youtube filter cleanup

---

src/applications/analytics/analytics-frame.component.ts
src/applications/analytics/analytics.component.ts
src/applications/content-entries-app/entries/entries-list-holder.component.ts
src/applications/content-entries-app/entry/entry-live/entry-live.component.html
src/applications/content-entries-app/entry/entry.component.html
src/applications/content-entries-app/entry/entry.component.ts

fix(analytics): remove realtime permissions

---

src/applications/content-entries-app/entry/entry-distribution/entry-distribution-widget.service.ts
src/applications/content-entries-app/entry/entry-flavours/entry-flavours-widget.service.ts

fix(entry/flavors): prevent KMC error when loading flavors without flavorParams

---

src/shared/content-shared/entries/entries-selector/entries-selector.component.scss

https://kaltura.atlassian.net/browse/KMCNG-2201

fix(content/playlists): Fix selected entries bucket style

---

src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.html
src/applications/content-drop-folders-app/drop-folders-list/drop-folders-list.component.scss
src/applications/content-drop-folders-app/drop-folders-refine-filters/drop-folders-refine-filters.component.scss

https://kaltura.atlassian.net/browse/KMCNG-2202

fix(content/drop-folders) Fix filter drop-down UI

---

package-lock.json

chore: update peer dependencies

---

src/applications/content-playlists-app/content-playlists-app.module.ts
src/applications/content-playlists-app/playlist/playlist-content/manual/bulk-operations/bulk-operations.component.html
src/applications/content-playlists-app/playlist/playlist-content/manual/bulk-operations/bulk-operations.component.ts
src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts
src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content.component.html
src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.html
src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.scss
src/applications/content-playlists-app/playlist/playlist-content/manual/playlist-entries-table/playlist-entries-table.component.ts
src/applications/content-playlists-app/playlist/playlist-details/playlist-details.component.html
src/applications/content-playlists-app/playlist/playlist-details/playlist-details.component.ts
src/applications/content-playlists-app/playlist/playlist.component.html
src/applications/content-playlists-app/playlist/playlist.component.scss
src/applications/content-playlists-app/playlist/playlist.component.ts
src/applications/content-playlists-app/playlists-utils.service.ts
src/applications/content-playlists-app/playlists/pipes/playlist-type.pipe.ts
src/applications/content-playlists-app/playlists/playlists-list/playlists-list.component.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.html
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.ts
src/applications/content-syndication-app/feeds/feeds.service.ts
src/i18n/en.json

feat(content/playlists): support Interactive Video entries (rapt playlists)

---

package-lock.json
package.json
src/applications/content-entries-app/entry/entry.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.scss
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-field-form/custom-schema-field-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.ts
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.html
src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema.component.ts
src/applications/settings-custom-data-app/schemas/pipes/metadata-object-type.pipe.ts
src/applications/settings-custom-data-app/schemas/schemas-store/schemas-store.service.ts
src/i18n/en.json
src/shared/kmc-shared/custom-metadata/kaltura-metadata-parser.ts
src/shared/kmc-shared/custom-metadata/metadata-profile.ts

https://kaltura.atlassian.net/browse/KMCNG-2204

feat(settings/metadata): Add User Entry metadata fields

---

kaltura-ws.json
src/applications/analytics/analytics-frame.component.ts
src/i18n/de.json
src/i18n/en.json
src/i18n/es.json
src/i18n/fr.json
src/i18n/ja.json

feat: Support Analytics localization

---

src/i18n/en.json

fixed src/i18n/en.json
Typo mistake 'Ipload'
fixed word with "Upload"
**Does this PR introduce a breaking change?** NO

chore: typo fix

---

package-lock.json
package.json
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-entries-data-provider.service.ts
src/i18n/en.json
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.ts
src/shared/content-shared/entries/entries-store/default-filters-list.ts
src/shared/content-shared/entries/entries-store/entries-store-data-provider.service.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

feat(content/entries): Filter entries list for entries with captions

---

src/shared/kmc-shared/custom-metadata/kaltura-metadata-parser.ts

fix(settings/custom-data): add support to complexType choice attribute

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/rule-based-content-widget.service.ts

fix(content/playlist): Fix entries count for rule-based playlist

---

src/applications/content-playlists-app/playlists/playlists-list/playlists-list.component.html
src/applications/content-playlists-app/playlists/playlists-list/playlists-list.component.scss
src/applications/content-playlists-app/playlists/playlists-refine-filters/playlists-refine-filters.component.html
src/applications/content-playlists-app/playlists/playlists-refine-filters/playlists-refine-filters.component.scss
src/applications/content-playlists-app/playlists/playlists-refine-filters/playlists-refine-filters.component.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/applications/content-playlists-app/playlists/playlists-tags/playlists-tags.component.ts

feat(content/playlists): Add Interactive Video filter

---

src/applications/content-entries-app/entry/entry-captions/entry-captions-widget.service.ts

chore(entry/captions): track accuracy changes made to old captions with no accuracy

---

package-lock.json
package.json
src/applications/content-playlists-app/playlist/playlist-content/manual/manual-content-widget.service.ts
src/applications/content-playlists-app/playlist/playlist-content/playlist-content.component.html
src/applications/content-playlists-app/playlists-utils.service.ts
src/applications/content-playlists-app/playlists/pipes/playlist-type.pipe.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.ts
src/shared/kmc-shared/kmc-views/details-views/content-playlist-view.service.ts

fix(content/playlists): support Path playlists

---

deploy_v7/README.md
deploy_v7/config.ini
deploy_v7/player.json
docs/kaltura-internal-docs/publish-kmc-ng-solution.md

chore: add v7 player deployment config

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-entries-data-provider.service.ts
src/i18n/en.json
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.ts
src/shared/content-shared/entries/entries-store/default-filters-list.ts
src/shared/content-shared/entries/entries-store/entries-store-data-provider.service.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

feat(content/entries): Filter for entries without captions

---

src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts

chore: list both rapt and path playlists in "Interactive Video" filter

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/shared/kmc-shared/kmc-views/component-views/advertisements-app-view.service.ts

chore: Handle advertising and category / playlist permissions on bulk actions

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-entries-data-provider.service.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule-parser.service.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule.component.scss
src/shared/content-shared/entries/entries-list/entries-list.component.html
src/shared/content-shared/entries/entries-list/entries-list.component.ts
src/shared/content-shared/entries/entries-search-filters/entries-search-filters.component.ts

fix for: https://kaltura.atlassian.net/browse/SUP-24606

fix(playlist/rule-based): Support eSearch free text field in playlist execution and save filter status SUP-24606

---

src/applications/content-entries-app/entry/entry-captions/entry-captions.component.ts

fix(entry/captions): support captions editor for WebVTT

---

src/applications/content-playlists-app/playlist/playlist.component.html
src/applications/content-playlists-app/playlist/playlist.component.ts
src/applications/content-playlists-app/playlists-utils.service.ts
src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.ts

chore: add analytics link to manual playlist

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-entries-data-provider.service.ts
src/i18n/en.json
src/shared/content-shared/entries/entries-list/entries-list-tags.component.ts
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.html
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.scss
src/shared/content-shared/entries/entries-refine-filters/entries-refine-filters.component.ts
src/shared/content-shared/entries/entries-store/entries-store-data-provider.service.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

feat(content/entries): add "Played Until" filter to entries list

---

src/applications/studio-app/studio-v3.component.ts
src/configuration/server-config.ts

chore(studio): Add optional playerConfVars property to Studio v3 configuration KMCNG-2295

---

src/applications/kmc-upload-app/create-live/create-live.service.ts
src/applications/kmc-upload-app/prepare-entry/prepare-entry.service.ts
src/shared/kmc-shell/new-entry-create-from-url/new-entry-create-from-url.service.ts
src/shared/kmc-shell/new-entry-upload/new-entry-upload.service.ts

fix(upload) - fill additional entry fields upon upload KMCNG-2308

---

src/applications/kmc-upload-app/create-live/kaltura-live-stream/kaltura-live-stream.component.ts

fix(create/live): disable record option if no permission for recording live stream KMCNG-2369

---

src/applications/kmc-upload-app/create-live/universal-live/universal-live.service.ts

fix(live stream): change universal live call to use new RxJS syntax KMCNG-2339

---

src/applications/content-categories-app/category/category-entitlements/category-entitlements-widget.service.ts

fix(entries/categories/edit): endless load of Entitlements tab (use new RxJS syntax) KMCNG-2335

---

src/applications/content-playlists-app/playlist/playlist-store.service.ts

fix(playlists/details): switch to next/previous playlist (left/right arrows) (new RxJS syntax) KMCNG-2328

---

src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-list/transcoding-profiles-list.component.scss

fix(settings/transcoding): table has wrong width on IE11 KMCNG-2322

---

src/shared/content-shared/categories/category-selector/category-selector.component.scss

fix(categories): After selecting another Category all of them disappear on Move Category KMCNG-2323

---

src/styles/app-theme/styles.scss

fix(entry): IE-11 - Back arrow cut-off in all relevant pages KMCNG-2340

---

angular.json
src/applications/content-entries-app/entry/entry-distribution/entry-distribution.component.scss

fix(entries/distribution): refresh button is cut off KMCNG-2320

---

src/applications/content-entries-app/entry/entry-distribution/edit-distribution-profile/edit-distribution-profile.component.scss
src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replace-file/replace-file.component.ts
src/kmc-app/components/app-menu/app-menu.component.scss
src/kmc-app/components/changelog/changelog.component.scss
src/shared/content-shared/categories/category-selector/category-selector.component.scss

fix(theme): style and RxJS fixes for Angular 11 KMCNG-2375

---

src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule-parser.service.ts

fix(playlists/rule based playlist): fix RxJS old syntax issues SUP-27709

---

src/i18n/en.json
src/kmc-app/components/login/password-expired-form/password-expired-form.component.html
src/kmc-app/components/login/password-expired-form/password-expired-form.component.ts

fix(login/expired password): add validation for new password to be different than old KMCNG-2377

---

src/applications/kmc-upload-app/create-live/create-live.component.ts
src/applications/kmc-upload-app/create-live/create-live.service.ts
src/applications/kmc-upload-app/create-live/manual-live/manual-live.component.html
src/applications/kmc-upload-app/create-live/manual-live/manual-live.component.ts
src/applications/kmc-upload-app/create-live/manual-live/manual-live.interface.ts
src/i18n/de.json
src/i18n/en.json
src/i18n/es.json
src/i18n/fr.json
src/i18n/ja.json
src/i18n/pt_br.json

fix(upload/manual-live): add support for DASH stream KMCNG-2376

---

src/applications/settings-integration-settings-app/zoom/generate-code/generate-code.component.ts

fix(settings/integration): zoom - copy code without break lines KMCNG-2382

---

src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/transcoding-profile-flavors-table/transcoding-profile-flavors-table.component.html
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/transcoding-profile-flavors-table/transcoding-profile-flavors-table.component.ts
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/transcoding-profile-flavors-widget.service.ts
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-flavors/transcoding-profile-flavors.component.html
src/applications/settings-transcoding-settings-app/transcoding-profile/transcoding-profile-metadata/transcoding-profile-metadata-widget.service.ts
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-table/transcoding-profiles-table.component.html
src/applications/settings-transcoding-settings-app/transcoding-profiles/transcoding-profiles-table/transcoding-profiles-table.component.ts
src/i18n/en.json

chore(settings/transcoding): disable actions with profiles on PartnerId 0 KMCNG-2383

---

package-lock.json
package.json
src/applications/analytics/analytics.component.ts
src/i18n/en.json
src/shared/kmc-shell/auth/app-authentication.service.ts
src/shared/kmc-shell/auth/app-user.ts

chore(analytics): add new usage dashboard routes

---

src/applications/settings-integration-settings-app/zoom/zoom.component.html
src/applications/settings-integration-settings-app/zoom/zoom.component.ts
src/i18n/en.json

fix(settings/integration): allow up to six zoom accounts KMCNG-2399

---

src/kmc-app/components/dashboard/dashboard.component.html
src/kmc-app/components/dashboard/dashboard.component.scss
src/kmc-app/components/dashboard/dashboard.component.ts

fix: display self serve on boarding video the first time the app loads KMCNG-2391

---

src/shared/kmc-shell/auth/app-authentication.service.ts

fix: end current session when switching account PLAT-23291

---

src/applications/analytics/analytics.component.ts
src/index.html
src/kmc-app/app.routes.ts
src/shared/kmc-shared/kmc-views/kmc-main-views.service.ts

fix(analytics): remove old usage dashboard and enable Analytics usage overview to all customers AN-22700, AN-22701

---

src/applications/administration-users-app/users/users-list.component.ts
src/kmc-app/app.component.html
src/kmc-app/components/user-settings/user-settings.component.html
src/kmc-app/components/user-settings/user-settings.component.ts
src/shared/kmc-shell/providers/kpf.service.ts

chore: use POST API for login to KPF with JWT KMCNG-2413

---

package-lock.json
package.json
src/applications/administration-users-app/administration-users-app.module.ts
src/applications/administration-users-app/users/edit-user/edit-user.component.html
src/applications/administration-users-app/users/edit-user/edit-user.component.ts
src/applications/administration-users-app/users/users.service.ts
src/i18n/en.json

feat(administration/users): allow excluding specific users from SSO login KMCNG-2417

---

src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-live/entry-live.component.html
src/applications/content-entries-app/entry/entry-live/entry-live.component.scss
src/applications/content-entries-app/entry/entry-live/entry-live.component.ts
src/i18n/en.json

feat(entry/live): SIP token generation KMCNG-2237

---

src/applications/settings-reach-app/reach-profile/reach-profile-dictionary/reach-profile-dictionary-widget.service.ts

fix(settings/reach): use the real length of data to avoid mismatch when exceeding 4000 chars SUP-28797

---

src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts

fix(entry/live): update primary and secondary SRT stream id when regenerating stream token KMCNG-2421

---

src/applications/administration-roles-app/roles-list/roles-list.component.ts
src/applications/administration-users-app/users/users-list.component.ts
src/applications/analytics/analytics-frame.component.ts
src/applications/content-categories-app/categories/categories-list/categories-list.component.html
src/applications/content-categories-app/categories/categories-list/categories-list.component.ts
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/content-entries-app/entries/entries-list-holder.component.ts
src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-live/entry-live.component.ts
src/applications/content-entries-app/entry/entry-preview/entry-preview.component.ts
src/applications/content-entries-app/entry/entry.component.ts
src/applications/content-playlists-app/playlists/playlists-list/playlists-list.component.ts
src/applications/kmc-upload-app/upload-button/upload-button.component.html
src/applications/kmc-upload-app/upload-button/upload-button.component.ts
src/configuration/server-config-schema.ts
src/configuration/server-config.ts
src/kmc-app/components/app-menu/app-menu.component.ts
src/kmc-app/components/changeAccount/change-account.component.ts
src/kmc-app/components/changelog/changelog.component.ts
src/kmc-app/components/login/login-form/login-form.component.ts
src/kmc-app/components/login/login.component.ts
src/kmc-app/components/login/sso-form/sso-form.component.ts
src/shared/content-shared/entries/entries-list/entries-list.component.html
src/shared/content-shared/entries/entries-list/entries-list.component.ts
src/shared/kmc-shell/kmc-shell.module.ts
src/shared/kmc-shell/providers/app-analytics.service.ts
src/shared/kmc-shell/providers/index.ts

chore: report kmc page load and button click events to analytics KMCNG-2427, KMCNG-2428

---

src/kmc-app/components/login/password-expired-form/password-expired-form.component.html
src/kmc-app/components/login/password-expired-form/password-expired-form.component.scss
src/kmc-app/components/login/password-expired-form/password-expired-form.component.ts

fix(login): display authenticator field for 2FA reset password form SUP-31938

---

package-lock.json
package.json
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.html
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.scss
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.ts
src/i18n/en.json

feat(zoom): manage zoom ingest to Kaltura (opt in/out) KMCNG-2423

---

src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.html
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.ts

fix(settings/integration): manage zoom ingest to Kaltura (opt in/out) KMCNG-2423

---

src/applications/content-entries-app/entry/entry-preview/entry-preview.component.html
src/applications/content-entries-app/entry/entry-preview/entry-preview.component.ts
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-capture.component.html
src/applications/content-entries-app/entry/entry-thumbnails/entry-thumbnails-capture.component.ts
src/public/playerWrapper.html

fix(content/entry): use playerWrapper to display entry preview + add preview context for internal logic + add live plugin to preview player SUP-33110

---

src/applications/content-playlists-app/playlists/playlists-store/playlists-store.service.ts
src/applications/content-playlists-app/playlists/playlists-table/playlists-table.component.ts

fix(content/playlists): use baseEntryList instead of playlistList action to support eSearch queries SUP-31434

---

src/applications/content-entries-app/entry/entry-captions/entry-captions.component.html
src/applications/content-entries-app/entry/entry-captions/entry-captions.component.ts
src/shared/kmc-shared/kmc-views/details-views/content-entry-view.service.ts
src/shared/kmc-shared/kmc-views/details-views/reach-app-view.service.ts

feat(content/entries): enable captions & enrich for live entries KMCNG-2456

---

src/applications/settings-access-control-app/profiles/edit-profile/edit-profile.component.scss

SUP-33042 change overflow to auto to allow scrolling in input text field

---

src/applications/content-entries-app/entry/entry-live/entry-live-widget.service.ts
src/applications/content-entries-app/entry/entry-live/entry-live.component.html
src/applications/content-entries-app/entry/entry-live/entry-live.component.scss
src/applications/content-entries-app/entry/entry-live/entry-live.component.ts
src/applications/kmc-upload-app/create-live/create-live.component.ts
src/applications/kmc-upload-app/create-live/create-live.service.ts
src/applications/kmc-upload-app/create-live/kaltura-live-stream/kaltura-live-stream.component.html
src/applications/kmc-upload-app/create-live/kaltura-live-stream/kaltura-live-stream.component.scss
src/applications/kmc-upload-app/create-live/kaltura-live-stream/kaltura-live-stream.component.ts
src/applications/kmc-upload-app/create-live/kaltura-live-stream/kaltura-live-stream.interface.ts
src/configuration/server-config-example.json
src/configuration/server-config.ts
src/i18n/en.json

feat(live): support low latency streams (beta) KMCNG-2460

---

src/applications/preview-and-embed/preview-and-embed.service.ts
src/applications/preview-and-embed/preview-embed.component.ts
src/public/playerWrapper.html

fix(share&embed): support v7 players for playlists KMCNG-2464

---

src/kmc-app/components/dashboard/dashboard.component.html
src/kmc-app/components/dashboard/dashboard.component.scss
src/kmc-app/components/dashboard/dashboard.component.ts
src/shared/kmc-shared/player-v7/player-v7.component.ts

chore: new studio promo screen KMCNG-2468

---

src/applications/content-categories-app/categories/categories-list/categories-list.component.html
src/applications/content-categories-app/categories/categories-list/categories-list.component.ts
src/applications/content-categories-app/categories/categories.service.ts
src/i18n/en.json

feat(content/categories): export categories to CSV - KMCNG-2440

---

src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-category-listing/bulk-change-category-listing.component.ts
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts
src/applications/content-categories-app/category/category-entitlements/change-owner/change-owner.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-editors/bulk-add-editors.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-publishers/bulk-add-publishers.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-viewers/bulk-add-viewers.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts
src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts
src/applications/settings-integration-settings-app/webex/edit-profile/edit-profile.component.ts
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.ts

fix(content/entry): user eSearch for users search SUP-35902

---

src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-category-listing/bulk-change-category-listing.component.ts
src/applications/content-categories-app/categories/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts
src/applications/content-categories-app/category/category-entitlements/change-owner/change-owner.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-editors/bulk-add-editors.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-publishers/bulk-add-publishers.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-add-viewers/bulk-add-viewers.component.ts
src/applications/content-entries-app/entries/bulk-actions/components/bulk-change-owner/bulk-change-owner.component.ts
src/applications/content-entries-app/entry/entry-users/entry-users-widget.service.ts
src/applications/settings-integration-settings-app/webex/edit-profile/edit-profile.component.ts
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.ts

fix(entry/user): fix user search logic SUP-35902

---

src/applications/settings-reach-app/reach-profiles/reach-services-store/reach-services-store.service.ts

fix(settings/reach): add pricePerUnit to query response profile SUP-37913

---

src/applications/preview-and-embed/preview-and-embed.service.ts
src/applications/preview-and-embed/preview-embed.component.ts
src/public/playerWrapper.html

feat(content/entry): support thumbnail embed for player v7 FEC-13351

---

src/i18n/en.json

fix(translations): change Slovenian to Slovene SUP-36739

---

src/applications/content-moderation-app/entry-report/entry-report.component.html
src/applications/content-moderation-app/entry-report/entry-report.component.scss
src/applications/content-moderation-app/entry-report/entry-report.component.ts

fix(entry/moderation): for moderated image entry: display image instead of player

---

src/applications/settings-authentication-app/edit-profile/edit-profile.component.html
src/applications/settings-authentication-app/edit-profile/edit-profile.component.ts
src/applications/settings-authentication-app/new-profile/new-profile.component.html
src/applications/settings-authentication-app/new-profile/new-profile.component.ts
src/applications/settings-authentication-app/profiles-list/profiles-list.component.ts
src/shared/kmc-shell/providers/app-analytics.service.ts

chore: auth profiles product analytics

---

src/applications/settings-integration-settings-app/settings-integration-settings-app.module.ts
src/applications/settings-integration-settings-app/settings-integration-settings.component.html
src/applications/settings-integration-settings-app/teams/edit-profile/edit-profile.component.html
src/applications/settings-integration-settings-app/teams/edit-profile/edit-profile.component.scss
src/applications/settings-integration-settings-app/teams/edit-profile/edit-profile.component.ts
src/applications/settings-integration-settings-app/teams/new-profile/new-profile.component.html
src/applications/settings-integration-settings-app/teams/new-profile/new-profile.component.scss
src/applications/settings-integration-settings-app/teams/new-profile/new-profile.component.ts
src/applications/settings-integration-settings-app/teams/profiles-table/profiles-table.component.html
src/applications/settings-integration-settings-app/teams/profiles-table/profiles-table.component.scss
src/applications/settings-integration-settings-app/teams/profiles-table/profiles-table.component.ts
src/applications/settings-integration-settings-app/teams/teams.component.html
src/applications/settings-integration-settings-app/teams/teams.component.scss
src/applications/settings-integration-settings-app/teams/teams.component.ts
src/applications/settings-integration-settings-app/teams/teams.service.ts
src/applications/settings-integration-settings-app/teams/update-secret/update-secret.component.html
src/applications/settings-integration-settings-app/teams/update-secret/update-secret.component.scss
src/applications/settings-integration-settings-app/teams/update-secret/update-secret.component.ts
src/applications/settings-integration-settings-app/webex/edit-profile/edit-profile.component.scss
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.scss
src/configuration/server-config.ts
src/i18n/en.json

feat(settings/integration): Teams Integration KMCNG-2584

---

src/applications/settings-mr-app/logs/logs-refine-filters/logs-refine-filters.component.ts
src/applications/settings-mr-app/logs/logs.component.ts
src/applications/settings-mr-app/review/review-refine-filters/review-refine-filters.component.html
src/applications/settings-mr-app/review/review-refine-filters/review-refine-filters.component.ts
src/applications/settings-mr-app/review/review.component.ts
src/applications/settings-mr-app/rule/actions/actions.component.ts
src/applications/settings-mr-app/rule/actions/renderers/delete.component.ts
src/applications/settings-mr-app/rule/actions/renderers/flavours.component.ts
src/applications/settings-mr-app/rule/actions/renderers/notification.component.ts
src/applications/settings-mr-app/rule/criteria/criteria.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/categories.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/created.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/duration.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/owner.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/played.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/plays.component.ts
src/applications/settings-mr-app/rule/criteria/renderers/tags.component.ts
src/applications/settings-mr-app/rule/rule.component.html
src/applications/settings-mr-app/rule/rule.component.ts
src/applications/settings-mr-app/rules/new-rule/new-rule.component.ts
src/applications/settings-mr-app/rules/rules.component.ts
src/configuration/server-config-example.json
src/shared/kmc-shell/providers/app-analytics.service.ts

chore: automation manager product analytics KMCNG-2583

---

.github/workflows/uiconf-deployment.yaml

- **testing release**
- **testing release**
- **add app name and tag inputs**
- **more inputs**
- **testing env var**
- **json parsing**
- **json parsing**
- **json parsing**
- **print repo name**
- **print repo name**
- **add repo name to inputs**
- **final curl**

workflow uiconf trigger

---

.github/workflows/upload-assets-to-s3.yaml

- **testing**
- **Remove external**
- **point to statboy master**
- **release trigger**

upload to s3

---

src/applications/content-entries-app/entry/entry-clips/entry-clips-widget.service.ts
src/applications/content-entries-app/entry/entry-clips/entry-clips.component.ts

fix: init content lab on live entries CR-105

---

src/applications/content-entries-app/entry/entry-quizzes/entry-quizzes-widget.service.ts
src/shared/kmc-shared/kedit-hoster/kedit-hoster.component.ts

fix(content/entry): refresh quiz list after closing quiz editor KMCNG-2689

---

deploy/config.ini
deploy_v7/config.ini
package.json
src/applications/content-entries-app/entry/entry-clips/entry-clips.component.ts
src/applications/content-entries-app/entry/entry-quizzes/entry-quizzes.component.ts
src/applications/content-entries-app/entry/entry.component.html
src/applications/content-entries-app/entry/entry.component.scss
src/applications/content-entries-app/entry/entry.component.ts
src/configuration/global-config.ts
src/kmc-app/components/changelog/changelog-content/changelog-content.component.html
src/shared/kmc-shell/auth/app-bootstrap.service.ts

feat: content lab refactor

---

src/applications/settings-integration-settings-app/teams/edit-profile/edit-profile.component.html
src/i18n/en.json

feat(setting/integration): support upload transcripts in Team profile settings KMCNG-2714

---

src/applications/settings-reach-app/reach-profiles/reach-services-list/reach-services-list.component.scss
src/applications/settings-reach-app/reach-profiles/reach-services-list/reach-services-list.component.ts
src/applications/settings-reach-app/reach-profiles/reach-services-store/reach-services-store.service.ts
src/i18n/en.json

fix: add ead to reach tab (SUP-43160)

---

package-lock.json
package.json
src/applications/administration-users-app/users/users-list.component.html
src/applications/administration-users-app/users/users-list.component.ts
src/applications/administration-users-app/users/users-table.component.ts
src/applications/administration-users-app/users/users.service.ts
src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/replacement-status/replacement-status.component.html
src/i18n/en.json

feat: user demote admin KMCNG-2721

---

src/applications/administration-users-app/users/users.service.ts

fix: add pager to fetch all roles (SUP-47566)

---

src/applications/content-entries-app/entry/entry.component.ts
src/shared/content-shared/entries/entries-list/entries-list.component.ts

fix: enable webcast analytics to all live entries KMCNG-2737

---

src/applications/administration-users-app/users/edit-user/edit-user.component.ts
src/applications/administration-users-app/users/users.service.ts

fix(settings/user): disable user id field for hashed users and do not send it on the update API call SUP-48407

---

package-lock.json
package.json
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.html
src/applications/settings-integration-settings-app/zoom/edit-profile/edit-profile.component.ts
src/shared/kmc-shell/auth/app-bootstrap.service.ts

feat(settings/integration): find user by email in Zoom integration KMCNG-2743

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts

fix(SUP-49493):  Error when deleting more than 25 entries

---

src/configuration/server-config-example.json

https://kaltura.atlassian.net/browse/KMCNG-2790

KMCNG-2790: update entitlement demo url

---

src/applications/settings-integration-settings-app/account-info/account-info.component.html
src/applications/settings-integration-settings-app/account-info/account-info.component.scss
src/applications/settings-integration-settings-app/account-info/account-info.component.ts
src/applications/settings-integration-settings-app/settings-integration-settings-app.module.ts
src/i18n/en.json

feat(settings/integration): Hide secrets in KMC GUI (KMCNG-2774)
