src/applications/content-entries-app/entry/entry-users/entry-users.component.html

fix: KMCNG-822 - Entry details: Users - missing tooltips and data display

---

src/applications/kmc-upload-app/prepare-entry/prepare-entry.component.html
src/applications/kmc-upload-app/prepare-entry/prepare-entry.component.ts

- [] Feature
Steps to reproduce:
a. Press on 'Create' button
b. Choose Video/Audio from 'Prepare Entry' section
Expected results:
'Transcoding Profile' screen is displayed
Actual results:
No 'Transcoding Profile' screen is displayed
Note:
in old KMC the drop-down is displayed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/325)

KMCNG-1172 Unable to choose 'Transcoding Profile' while preparing entry

---

src/applications/content-categories-app/categories/categories.service.ts
src/applications/content-categories-app/categories/new-category/new-category.component.ts
src/i18n/en.json

- kmcng-1279
- kmcng-1266
- kmcng-1267
- remove navigate confirmation upon successful creation of category.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/386)

handle creation errors correctly

---

src/applications/content-entries-app/content-entries.component.ts
src/applications/content-entries-app/entries/entries-list-holder.component.ts
src/applications/content-moderation-app/content-moderation.component.ts
src/applications/content-moderation-app/entries/entries-list-holder.component.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-entries-data-provider.service.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule.component.ts
src/shared/content-shared/entries/entries-selector/entries-selector.component.ts
src/shared/content-shared/entries/entries-store/entries-store-data-provider.service.ts
src/shared/content-shared/entries/entries-store/entries-store.service.ts

- [] Feature
Show rows param always was resetting to default value when user leaves entries-list page
Use injection token to define pagination cache key to prevent current behavior
- [] Yes
- [] No
---
**How …

Fix entries-list pagination cache token

---

src/applications/content-categories-app/categories/bulk-actions/categories-bulk-actions.component.ts
src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/applications/kmc-upload-app/prepare-entry/prepare-entry.component.ts
src/kmc-app/app.component.html
src/kmc-app/app.component.ts
src/shared/kmc-shell/providers/browser.service.ts

- [] Bugfix
- [] Feature
Some parts of the code were using `setAppStatus` function of the `BrowserService`
Remove `setAppStatus` function, replace its calls with `alert` function
- [] Yes
- [] No
---
**How should …

Remove setAppStatus, replace with alert

---

src/applications/settings-custom-data-app/schemas/custom-schema/custom-schema-form/custom-schema-form.component.ts

New custom data schemas always are applied to entries
Fix apply to switching
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/486)

Custom Data > Fix applyTo always set to entries

---

src/kmc-app/app.module.ts
src/kmc-app/app.routes.ts
src/kmc-app/components/login/login-actions/login-actions.component.ts
src/shared/kmc-shell/auth/app-authentication.service.ts

A user can login into the app using login actions and ks.
To log in with the ks type `[domain]/login/actions/login-by-ks?ks=[token]` into url field of the browser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/604)

Allow user login by ks in query params

---

src/shared/content-shared/entries/entries-table/entries-table.component.html

`[ngStyle]` is used to apply column style fails to work (styles are not applied)
Replace `[ngStyle]` with `[style]` for entries table
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/694)

Fix entries table columns styles

---

src/kmc-app/components/app-menu/app-menu.component.html
src/kmc-app/components/app-menu/app-menu.component.ts
src/kmc-app/components/changelog/changelog.component.html
src/kmc-app/components/changelog/changelog.component.ts

Changelog notification is shown only when info popup is opened
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/700)

Fix changelog notification

---

src/applications/content-playlists-app/playlist/playlist-add-entry/playlist-add-entry.component.ts
src/applications/content-playlists-app/playlist/playlist-content/rule-based/playlist-rule/playlist-rule.component.ts
src/shared/content-shared/entries/link-entries-selector/linked-entries-add-entries/linked-entries-add-entries.component.ts

The app crashes in
* rulebased playlist > add/edit rule popup
* manual playlist > add entries popup
* entry details > metadata > add linked entries
Provide missing services to prevent crash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/777)

Fix resizable tables crash

---

src/shared/kmc-shared/kedit-hoster/kedit-hoster.component.ts

When removing the clipping permissions from a partner, when opening KEA for clip and trip, you see "Save" disabled, and "Save a copy" enabled in the Save menu
https://kaltura.atlassian.net/browse/KMCNG-1968
**Save a copy** button should not be shown 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kaltura/kmc-ng/775)

KMCNG-1968

---

src/applications/content-syndication-app/feeds/feed-details/feed-details.component.ts
src/applications/content-syndication-app/feeds/feeds.service.ts
src/i18n/en.json

* https://kaltura.atlassian.net/browse/SUP-17726
* Also handled trying to open a feed using a deleted playlist
* feeds which use a playlist which is not loaded in the first 500 playlists are returned properly
* trying to open a feed using a deleted playlist results in the correct error message
No

fix(content/syndication): Handle Syndication feeds which use a playlist which is not loaded in the first 500 playlists

---

src/shared/kmc-shared/server-polls/kmc-server-polls.service.ts

https://kaltura.atlassian.net/browse/KMCNG-2110
After the KS expires the app keeps sending requests to the server with invalid KS
After the client receives INVALID_KS error code for the server polls requests iteration, it stops sending any polls requests as they all will faile with the same error.

fix: Server poll invalid KS handling

---

src/applications/preview-and-embed/preview-embed.component.ts

The link 'Standalone Preview' located in 'Share & Embed' is not correct.
To the method 'createPreviewLink' was always passing the param isPreview = false,
this method doesn't need to receive isPreview value, isPreview has to be always true
Small issue in the method 'flashVarsToUrl', the & was added also for the first param of the URL
Fixed the method 'createPreviewLink' removing the input parameter 'isPreview' and setting to true where was used.
Fixed the method 'flashVarsToUrl' adding the & only for the params after the first
NO

fixed 'Standalone Preview' link

---

src/shared/content-shared/entries/entries-table/entries-table.component.html
src/shared/content-shared/entries/entries-table/entries-table.component.ts

when failing to load entry thumbnail - try one more time with ks and if failing again - display no thumbnail icon

fix(content/entries): Load thumbnails for entries with access control profile requiring KS to show thumbnail

---

src/shared/content-shared/entries/entries-list/entries-list.component.scss

Eliminated 'align-items' which has no support on old browsers, and changed 'padding-top' to 'padding-bottom' for the same behavior.
Layout breaks while using an old browser or specifically IE 11.
The layout should be the same on all browsers.
No

style: Swapped padding-top to padding-bottom for IE

---

src/applications/analytics/analytics-frame.component.ts

fix(category/analytics): Update Analytics queryParams upon switching IDs in the same route

---

src/applications/content-entries-app/entry/entry-live/entry-live.component.html

When there is no backup servers for live, errors are thrown and page doesn't render correctly.
URLs cannot be copied and used.
Avoiding actions on the missing parameter from the API call. page renders as expected and empty fields are empty.
No.

KMCNG-2366: Ignore empty secondaryRtspBroadcastingUrl

---

src/applications/content-entries-app/entry/entry-flavours/flavor-replace-video/match-drop-folder/match-drop-folder.component.ts

fix(entry/flavors): Match from Drop Folder error due to old RxJS syntax (use new RxJS syntax)

---

src/applications/content-entries-app/entry/entry-captions/entry-captions.component.html
src/applications/content-entries-app/entry/entry-captions/entry-captions.component.ts

fix(entry/captions): add delete menu option to broken caption KMCNG-2381

---

src/kmc-app/components/changeAccount/change-account.component.html

JIRA ticket: https://kaltura.atlassian.net/browse/KMCNG-2414
In the "Change Account" dialog box, the list contains only the partner name.
Add partner IDs to each of the partner names:
(Maybe it's not a common use case, but it might be helpful for some people)
No.

chore(change-account): add partner ID to the list of partners

---

src/applications/settings-reach-app/reach-profile/reach-profile-dictionary/reach-profile-dictionary-widget.service.ts

Reach dictionary max chars is 4000.
Reach dictionary max chars is 8000.

SUP-35187 Increase reach dictionary max chars to 8000

---

src/applications/content-entries-app/entries/bulk-actions/bulk-actions.component.ts
src/i18n/en.json

**Issue:**
Delete more than 25 entries in once is not allowed and the customer doesn't have an input for that.
**Fix:**
Add a warning message.

fix(SUP-49493): KMC - Error when deleting more than 25 entries 
